package generator

import (
	"sort"
	"strings"

	ogengen "github.com/ogen-go/ogen/gen"
	"github.com/ogen-go/ogen/gen/ir"
	"github.com/yaroher/protoc-gen-ogen/ogen"
	"google.golang.org/protobuf/compiler/protogen"
)

const grpcbridgeImport = protogen.GoImportPath("github.com/yaroher/protoc-gen-ogen/grpcbridge")

// opMethod links an ogen operation to the proto service/method it came from.
type opMethod struct {
	svc    *protogen.Service
	method *protogen.Method
	opts   *ogen.MethodOptions
}

// generateAdapter emits an OgenAdapter that implements the ogen Handler interface
// by delegating to the gRPC service implementations (protoc-gen-go-grpc output).
func (g *OpenAPIGenerator) generateAdapter(file *protogen.File, fileOpts *ogen.FileOptions, gen *ogengen.Generator) {
	// Map operationId -> proto service/method (HTTP, non-webhook operations).
	byOpID := map[string]opMethod{}
	for _, svc := range file.Services {
		so := getServiceOptions(svc)
		if so != nil && so.GetOmit() {
			continue
		}
		for _, m := range svc.Methods {
			mo := getMethodOptions(m)
			if mo == nil || mo.GetOmit() || mo.GetHttpMethod() == ogen.HttpMethod_HTTP_METHOD_UNSPECIFIED {
				continue
			}
			if mo.GetWebhook().GetName() != "" {
				continue // webhooks handled separately (phase 2)
			}
			byOpID[operationID(svc, m, mo)] = opMethod{svc: svc, method: m, opts: mo}
		}
	}

	// Match ogen operations to proto methods.
	type pair struct {
		op *ir.Operation
		om opMethod
	}
	var pairs []pair
	usedSvc := map[*protogen.Service]bool{}
	for _, op := range gen.Operations() {
		om, ok := byOpID[op.Spec.OperationID]
		if !ok {
			continue
		}
		pairs = append(pairs, pair{op: op, om: om})
		usedSvc[om.svc] = true
	}
	if len(pairs) == 0 {
		return
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].op.Name < pairs[j].op.Name })

	var svcs []*protogen.Service
	for _, svc := range file.Services {
		if usedSvc[svc] {
			svcs = append(svcs, svc)
		}
	}

	gf := g.Plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".ogenadapter.go", file.GoImportPath)
	gf.P("// Code generated by protoc-gen-ogen. DO NOT EDIT.")
	gf.P()
	gf.P("package ", string(file.GoPackageName))
	gf.P()

	a := &adapterGen{
		convGen: &convGen{gf: gf, ogenImport: protogen.GoImportPath(fileOpts.GetOgenPackage())},
	}

	// Adapter struct + constructor.
	a.gf.P("// OgenAdapter implements the ogen Handler by delegating to gRPC services.")
	a.gf.P("type OgenAdapter struct {")
	for _, svc := range svcs {
		a.gf.P(svcField(svc), " ", svc.GoName, "Server")
	}
	a.gf.P("}")
	a.gf.P()
	a.gf.P("// NewOgenAdapter builds an OgenAdapter from the gRPC service implementations.")
	a.gf.P("func NewOgenAdapter(")
	for _, svc := range svcs {
		a.gf.P(svcField(svc), " ", svc.GoName, "Server,")
	}
	a.gf.P(") *OgenAdapter {")
	a.gf.P("return &OgenAdapter{")
	for _, svc := range svcs {
		a.gf.P(svcField(svc), ": ", svcField(svc), ",")
	}
	a.gf.P("}")
	a.gf.P("}")
	a.gf.P()

	for _, p := range pairs {
		a.genMethod(p.op, p.om)
	}

	a.genNewError(gen)

	// Compile-time check that the adapter implements the ogen Handler.
	a.gf.P("var _ ", a.oid("Handler"), " = (*OgenAdapter)(nil)")
	a.gf.P()
}

type adapterGen struct {
	*convGen
}

func svcField(svc *protogen.Service) string {
	return lowerFirst(svc.GoName)
}

// genMethod renders one ogen Handler method delegating to the gRPC method.
func (a *adapterGen) genMethod(op *ir.Operation, om opMethod) {
	a.tmp = 0
	pass := op.Responses.DoPass()
	a.fail = "nil"
	failRet := "nil, "
	if !pass {
		failRet = ""
	}

	// Signature: Name(ctx context.Context[, req <ReqGoType>][, params <Name>Params]) <result>
	sig := "func (a *OgenAdapter) " + op.Name + "(ctx " + a.qual(protogen.GoIdent{GoName: "Context", GoImportPath: "context"})
	if op.Request != nil {
		sig += ", req " + a.reqGoType(op.Request.Type)
	}
	if len(op.Params) > 0 {
		sig += ", params " + a.qual(a.oid(op.Name+"Params"))
	}
	sig += ") "
	if pass {
		sig += "(" + a.reqGoType(op.Responses.Type) + ", error) {"
	} else {
		sig += "error {"
	}
	a.gf.P(sig)

	input := om.method.Input
	a.gf.P("in := &", om.method.Input.GoIdent, "{}")

	// Request body.
	if op.Request != nil {
		a.genRequestBody(om, input, failRet)
	}
	// Parameters (-> proto fields, headers also -> metadata).
	a.genParams(op, om, input)

	// Call the gRPC method.
	a.gf.P("resp, err := a.", svcField(om.svc), ".", om.method.GoName, "(ctx, in)")
	a.gf.P("if err != nil {")
	a.gf.P("return ", failRet, "err")
	a.gf.P("}")

	if !pass {
		a.gf.P("_ = resp")
		a.gf.P("return nil")
		a.gf.P("}")
		a.gf.P()
		return
	}
	a.genResponse(om, failRet)
	a.gf.P("}")
	a.gf.P()
}

// genRequestBody converts the ogen request body into the proto request.
func (a *adapterGen) genRequestBody(om opMethod, input *protogen.Message, failRet string) {
	body := om.opts.GetRequestBody()
	if body == nil {
		return
	}
	fp := body.GetFieldPath()
	if fp == "" {
		a.gf.P("b, err := ", input.GoIdent.GoName, "FromOgen(req)")
		a.gf.P("if err != nil {")
		a.gf.P("return ", failRet, "err")
		a.gf.P("}")
		a.gf.P("in = b")
		return
	}
	field := findField(input, fp)
	if field == nil || field.Message == nil {
		return
	}
	a.gf.P("b, err := ", field.Message.GoIdent.GoName, "FromOgen(req)")
	a.gf.P("if err != nil {")
	a.gf.P("return ", failRet, "err")
	a.gf.P("}")
	a.gf.P("in.", field.GoName, " = b")
}

// genParams sets proto fields from ogen params and mirrors header params to metadata.
func (a *adapterGen) genParams(op *ir.Operation, om opMethod, input *protogen.Message) {
	paramByName := map[string]*ir.Parameter{}
	for _, p := range op.Params {
		if p.Spec != nil {
			paramByName[p.Spec.Name] = p
		}
	}
	for _, binding := range om.opts.GetParameters() {
		field := findField(input, binding.GetFieldPath())
		if field == nil || field.Desc.IsList() || field.Desc.IsMap() {
			continue // list/map params unsupported in phase 1
		}
		p := paramByName[parameterName(binding, field)]
		if p == nil {
			continue
		}
		inner, wrapped := unwrapGeneric(p.Type)
		if wrapped {
			a.gf.P("if v, ok := params.", p.Name, ".Get(); ok {")
			a.setParamField(field, inner, "v", binding)
			a.gf.P("}")
		} else {
			a.setParamField(field, inner, "params."+p.Name, binding)
		}
	}
}

func (a *adapterGen) setParamField(field *protogen.Field, inner *ir.Type, src string, binding *ogen.ParameterBinding) {
	expr, ok := a.fromOgenInner(field, inner, src)
	if !ok {
		return
	}
	if field.Message == nil && field.Desc.HasPresence() {
		// proto3 optional scalar/enum field is a pointer.
		p := a.newTmp("p")
		a.gf.P(p, " := ", expr)
		a.gf.P("in.", field.GoName, " = &", p)
	} else {
		a.gf.P("in.", field.GoName, " = ", expr)
	}
	if binding.GetIn() == ogen.ParameterLocation_PARAMETER_LOCATION_HEADER {
		header := firstNonEmpty(binding.GetName(), "X-"+field.GoName)
		a.gf.P("ctx = ", a.qual(protogen.GoIdent{GoName: "AppendIncomingMD", GoImportPath: grpcbridgeImport}),
			"(ctx, ", strconvQuote(header), ", ", a.mdString(inner, src), ")")
	}
}

// genResponse extracts the success body from the gRPC response and converts it.
func (a *adapterGen) genResponse(om opMethod, failRet string) {
	fp := successFieldPath(om.opts)
	src := "resp"
	if fp != "" {
		if field := findField(om.method.Output, fp); field != nil {
			src = "resp.Get" + field.GoName + "()"
		}
	}
	a.gf.P("out, err := ", src, ".ToOgen()")
	a.gf.P("if err != nil {")
	a.gf.P("return ", failRet, "err")
	a.gf.P("}")
	a.gf.P("return out, nil")
}

// genNewError maps gRPC status codes/messages/details onto the ogen error type.
func (a *adapterGen) genNewError(gen *ogengen.Generator) {
	errType := ogenErrorType(gen)
	a.gf.P("// NewError converts a gRPC error into the ogen error response.")
	a.gf.P("func (a *OgenAdapter) NewError(ctx ", a.qual(protogen.GoIdent{GoName: "Context", GoImportPath: "context"}), ", err error) *", a.oid("ErrorStatusCode"), " {")
	a.gf.P("st := ", a.qual(protogen.GoIdent{GoName: "Status", GoImportPath: grpcbridgeImport}), "(err)")
	a.gf.P("e := ", a.oid("Error"), "{}")
	if errType != nil {
		for _, f := range errType.Fields {
			switch f.Tag.JSON {
			case "code":
				a.gf.P("e.", f.Name, " = st.Code().String()")
			case "message":
				a.gf.P("e.", f.Name, " = st.Message()")
			case "details":
				if f.Type.Is(ir.KindArray) {
					a.gf.P("e.", f.Name, " = ", a.qual(protogen.GoIdent{GoName: "Details", GoImportPath: grpcbridgeImport}), "(st)")
				}
			}
		}
	}
	a.gf.P("return &", a.oid("ErrorStatusCode"), "{")
	a.gf.P("StatusCode: ", a.qual(protogen.GoIdent{GoName: "HTTPStatus", GoImportPath: grpcbridgeImport}), "(st.Code()),")
	a.gf.P("Response: e,")
	a.gf.P("}")
	a.gf.P("}")
	a.gf.P()
}

// reqRespGoType mirrors ogen: pointer for pass-by-pointer types.
func (a *adapterGen) reqGoType(t *ir.Type) string {
	if t.DoPassByPointer() {
		return "*" + a.goType(t)
	}
	return a.goType(t)
}

func (a *adapterGen) mdString(t *ir.Type, src string) string {
	switch {
	case externalImports[t.Go()] != "":
		return src + ".String()"
	case t.Is(ir.KindPrimitive) && t.Go() == "string":
		return src
	default:
		return a.qual(protogen.GoIdent{GoName: "Sprint", GoImportPath: "fmt"}) + "(" + src + ")"
	}
}

func operationID(svc *protogen.Service, m *protogen.Method, opts *ogen.MethodOptions) string {
	return firstNonEmpty(opts.GetOperationId(), lowerFirst(string(svc.Desc.Name()))+string(m.Desc.Name()))
}

func parameterName(binding *ogen.ParameterBinding, field *protogen.Field) string {
	if binding.GetName() != "" {
		return binding.GetName()
	}
	if field != nil {
		return jsonName(field)
	}
	return binding.GetFieldPath()
}

func successFieldPath(opts *ogen.MethodOptions) string {
	for _, r := range opts.GetResponses() {
		if r.GetStatus() >= 200 && r.GetStatus() < 300 {
			return r.GetFieldPath()
		}
	}
	return ""
}

// ogenErrorType returns the ogen type used as ErrorStatusCode.Response.
func ogenErrorType(gen *ogengen.Generator) *ir.Type {
	for _, t := range gen.Types() {
		if t.Name != "ErrorStatusCode" {
			continue
		}
		for _, f := range t.Fields {
			if f.Name == "Response" {
				return f.Type
			}
		}
	}
	return nil
}

func strconvQuote(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }
