package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/gopherex/protoc-gen-go-ogen/ogen"
	ogengen "github.com/ogen-go/ogen/gen"
	"github.com/ogen-go/ogen/gen/ir"
	"google.golang.org/protobuf/compiler/protogen"
)

const grpcbridgeImport = protogen.GoImportPath("github.com/gopherex/protoc-gen-go-ogen/grpcbridge")

// opMethod links an ogen operation to the proto service/method it came from.
type opMethod struct {
	svc    *protogen.Service
	method *protogen.Method
	opts   *ogen.MethodOptions
}

// generateAdapter emits an OgenAdapter that implements the ogen Handler interface
// by delegating to the gRPC service implementations (protoc-gen-go-grpc output).
func (g *OpenAPIGenerator) generateAdapters(files []*protogen.File, fileOpts *ogen.FileOptions, gen *ogengen.Generator) error {
	groups := map[protogen.GoImportPath][]*protogen.File{}
	var order []protogen.GoImportPath
	for _, file := range files {
		if _, ok := groups[file.GoImportPath]; !ok {
			order = append(order, file.GoImportPath)
		}
		groups[file.GoImportPath] = append(groups[file.GoImportPath], file)
	}
	if len(order) > 1 {
		return fmt.Errorf("generate_grpc_adapter with aggregate OpenAPI requires all marked files to share one go_package; got %d go packages", len(order))
	}
	for _, importPath := range order {
		g.generateAdapterGroup(groups[importPath], fileOpts, gen)
	}
	return nil
}

func (g *OpenAPIGenerator) generateAdapterGroup(files []*protogen.File, fileOpts *ogen.FileOptions, gen *ogengen.Generator) {
	if len(files) == 0 {
		return
	}
	root := files[0]
	// Map operationId -> proto service/method (HTTP, non-webhook operations).
	byOpID := map[string]opMethod{}
	for _, file := range files {
		for _, svc := range file.Services {
			so := getServiceOptions(svc)
			if so != nil && so.GetOmit() {
				continue
			}
			for _, m := range svc.Methods {
				mo := getMethodOptions(m)
				if mo == nil || mo.GetOmit() || mo.GetHttpMethod() == ogen.HttpMethod_HTTP_METHOD_UNSPECIFIED {
					continue
				}
				byOpID[operationID(svc, m, mo)] = opMethod{svc: svc, method: m, opts: mo}
			}
		}
	}

	// Match ogen operations (paths and webhooks) to proto methods.
	type pair struct {
		op *ir.Operation
		om opMethod
	}
	usedSvc := map[*protogen.Service]bool{}
	collectPairs := func(ops []*ir.Operation) []pair {
		var out []pair
		for _, op := range ops {
			om, ok := byOpID[op.Spec.OperationID]
			if !ok {
				continue
			}
			out = append(out, pair{op: op, om: om})
			usedSvc[om.svc] = true
		}
		sort.Slice(out, func(i, j int) bool { return out[i].op.Name < out[j].op.Name })
		return out
	}
	pairs := collectPairs(gen.Operations())
	webhookPairs := collectPairs(gen.Webhooks())
	if len(pairs) == 0 && len(webhookPairs) == 0 {
		return
	}

	var svcs []*protogen.Service
	for _, file := range files {
		for _, svc := range file.Services {
			if usedSvc[svc] {
				svcs = append(svcs, svc)
			}
		}
	}

	gf := g.Plugin.NewGeneratedFile(root.GeneratedFilenamePrefix+".ogenadapter.go", root.GoImportPath)
	gf.P("// Code generated by protoc-gen-ogen. DO NOT EDIT.")
	gf.P()
	gf.P("package ", string(root.GoPackageName))
	gf.P()

	a := &adapterGen{
		convGen: &convGen{gf: gf, ogenImport: protogen.GoImportPath(fileOpts.GetOgenPackage())},
	}

	// Adapter struct + constructor.
	a.gf.P("// OgenAdapter implements the ogen Handler by delegating to gRPC services.")
	a.gf.P("type OgenAdapter struct {")
	for _, svc := range svcs {
		a.gf.P(svcField(svc), " ", svc.GoName, "Server")
	}
	a.gf.P("}")
	a.gf.P()
	a.gf.P("// NewOgenAdapter builds an OgenAdapter from the gRPC service implementations.")
	a.gf.P("func NewOgenAdapter(")
	for _, svc := range svcs {
		a.gf.P(svcField(svc), " ", svc.GoName, "Server,")
	}
	a.gf.P(") *OgenAdapter {")
	a.gf.P("return &OgenAdapter{")
	for _, svc := range svcs {
		a.gf.P(svcField(svc), ": ", svcField(svc), ",")
	}
	a.gf.P("}")
	a.gf.P("}")
	a.gf.P()

	for _, p := range pairs {
		a.genMethod(p.op, p.om)
	}
	for _, p := range webhookPairs {
		a.genMethod(p.op, p.om)
	}

	a.genNewError(gen)

	// Compile-time checks that the adapter implements the ogen interfaces.
	if len(pairs) > 0 {
		a.gf.P("var _ ", a.oid("Handler"), " = (*OgenAdapter)(nil)")
	}
	if len(webhookPairs) > 0 {
		a.gf.P("var _ ", a.oid("WebhookHandler"), " = (*OgenAdapter)(nil)")
	}
	a.gf.P()
}

type adapterGen struct {
	*convGen
}

func svcField(svc *protogen.Service) string {
	return lowerFirst(svc.GoName)
}

// genMethod renders one ogen Handler method delegating to the gRPC method.
func (a *adapterGen) genMethod(op *ir.Operation, om opMethod) {
	a.tmp = 0
	pass := op.Responses.DoPass()
	a.fail = "nil"
	failRet := "nil, "
	if !pass {
		failRet = ""
	} else if op.Responses.Type != nil && !op.Responses.Type.DoPassByPointer() {
		// The success type is returned by value (e.g. server-streaming
		// rest.StreamLogsOK), so its zero value — not nil — is the failure
		// return. Pointer/interface success types keep "nil".
		failRet = a.goType(op.Responses.Type) + "{}, "
	}

	// Signature: Name(ctx context.Context[, req <ReqGoType>][, params <Name>Params]) <result>
	sig := "func (a *OgenAdapter) " + op.Name + "(ctx " + a.qual(protogen.GoIdent{GoName: "Context", GoImportPath: "context"})
	if op.Request != nil {
		sig += ", req " + a.reqGoType(op.Request.Type)
	}
	if len(op.Params) > 0 {
		sig += ", params " + a.qual(a.oid(op.Name+"Params"))
	}
	sig += ") "
	if pass {
		sig += "(" + a.reqGoType(op.Responses.Type) + ", error) {"
	} else {
		sig += "error {"
	}
	a.gf.P(sig)

	input := om.method.Input
	a.gf.P("in := &", om.method.Input.GoIdent, "{}")

	// Request body.
	if op.Request != nil {
		a.genRequestBody(om, input, failRet)
	}
	// Parameters (-> proto fields, headers also -> metadata).
	a.genParams(op, om, input)

	// Call the gRPC method.
	if om.method.Desc.IsStreamingServer() {
		a.genServerStreamResponse(op, om)
		a.gf.P("}")
		a.gf.P()
		return
	}
	a.gf.P("resp, err := a.", svcField(om.svc), ".", om.method.GoName, "(ctx, in)")
	a.gf.P("if err != nil {")
	a.gf.P("return ", failRet, "err")
	a.gf.P("}")

	if !pass {
		a.gf.P("_ = resp")
		a.gf.P("return nil")
		a.gf.P("}")
		a.gf.P()
		return
	}
	a.genResponse(op, om, failRet)
	a.gf.P("}")
	a.gf.P()
}

// genRequestBody converts the ogen request body into the proto request.
func (a *adapterGen) genRequestBody(om opMethod, input *protogen.Message, failRet string) {
	body := om.opts.GetRequestBody()
	if body == nil {
		return
	}
	fp := body.GetFieldPath()
	if fp == "" {
		a.gf.P("b, err := ", input.GoIdent.GoName, "FromOgen(req)")
		a.gf.P("if err != nil {")
		a.gf.P("return ", failRet, "err")
		a.gf.P("}")
		a.gf.P("in = b")
		return
	}
	field := findField(input, fp)
	if field == nil || field.Message == nil {
		return
	}
	a.gf.P("b, err := ", field.Message.GoIdent.GoName, "FromOgen(req)")
	a.gf.P("if err != nil {")
	a.gf.P("return ", failRet, "err")
	a.gf.P("}")
	a.gf.P("in.", field.GoName, " = b")
}

// genParams sets proto fields from ogen params and mirrors header params to metadata.
func (a *adapterGen) genParams(op *ir.Operation, om opMethod, input *protogen.Message) {
	paramByName := map[string]*ir.Parameter{}
	for _, p := range op.Params {
		if p.Spec != nil {
			paramByName[p.Spec.Name] = p
		}
	}
	for _, binding := range om.opts.GetParameters() {
		field := findField(input, binding.GetFieldPath())
		if field == nil || field.Desc.IsList() || field.Desc.IsMap() {
			continue // list/map params unsupported in phase 1
		}
		p := paramByName[parameterName(binding, field)]
		if p == nil {
			continue
		}
		inner, wrapped := unwrapGeneric(p.Type)
		if wrapped {
			a.gf.P("if v, ok := params.", p.Name, ".Get(); ok {")
			a.setParamField(field, inner, "v", binding)
			a.gf.P("}")
		} else {
			a.setParamField(field, inner, "params."+p.Name, binding)
		}
	}
}

func (a *adapterGen) setParamField(field *protogen.Field, inner *ir.Type, src string, binding *ogen.ParameterBinding) {
	expr, ok := a.fromOgenInner(field, inner, src)
	if !ok {
		return
	}
	if field.Message == nil && field.Desc.HasPresence() {
		// proto3 optional scalar/enum field is a pointer.
		p := a.newTmp("p")
		a.gf.P(p, " := ", expr)
		a.gf.P("in.", field.GoName, " = &", p)
	} else {
		a.gf.P("in.", field.GoName, " = ", expr)
	}
	if binding.GetIn() == ogen.ParameterLocation_PARAMETER_LOCATION_HEADER {
		header := firstNonEmpty(binding.GetName(), "X-"+field.GoName)
		a.gf.P("ctx = ", a.qual(protogen.GoIdent{GoName: "AppendIncomingMD", GoImportPath: grpcbridgeImport}),
			"(ctx, ", strconvQuote(header), ", ", a.mdString(inner, src), ")")
	}
}

// genResponse returns the success result: a no-content variant struct, or the
// success body field converted via ToOgen.
func (a *adapterGen) genResponse(op *ir.Operation, om opMethod, failRet string) {
	if sr := successIRResponse(op); sr != nil && sr.NoContent != nil && len(sr.Contents) == 0 {
		a.gf.P("_ = resp")
		a.gf.P("return &", a.oid(sr.NoContent.Name), "{}, nil")
		return
	}
	fp := successFieldPath(om.opts)
	src := "resp"
	if fp != "" {
		if field := findField(om.method.Output, fp); field != nil {
			src = "resp.Get" + field.GoName + "()"
		}
	}
	a.gf.P("out, err := ", src, ".ToOgen()")
	a.gf.P("if err != nil {")
	a.gf.P("return ", failRet, "err")
	a.gf.P("}")
	a.gf.P("return out, nil")
}

func (a *adapterGen) genServerStreamResponse(op *ir.Operation, om opMethod) {
	t := successStreamType(op)
	if t == nil {
		a.gf.P("return nil, ", a.qual(protogen.GoIdent{GoName: "Errorf", GoImportPath: "fmt"}), "(\"server-streaming operation has no stream response\")")
		return
	}
	a.gf.P("reader := ", a.qual(protogen.GoIdent{GoName: "ServerSentEventReader", GoImportPath: grpcbridgeImport}),
		"(func(w ", a.qual(protogen.GoIdent{GoName: "Writer", GoImportPath: "io"}), ") error {")
	a.gf.P("stream := ", a.qual(protogen.GoIdent{GoName: "NewServerSentEventStream", GoImportPath: grpcbridgeImport}),
		"[", om.method.Output.GoIdent, "](ctx, w)")
	a.gf.P("return a.", svcField(om.svc), ".", om.method.GoName, "(in, stream)")
	a.gf.P("})")
	expr := a.goType(t) + "{Data: reader}"
	if op.Responses.Type != t {
		expr = "&" + expr
	}
	a.gf.P("return ", expr, ", nil")
}

// successIRResponse returns the 2xx ogen response for an operation, if any.
func successIRResponse(op *ir.Operation) *ir.Response {
	if op.Responses == nil {
		return nil
	}
	for code, r := range op.Responses.StatusCode {
		if code >= 200 && code < 300 {
			return r
		}
	}
	return op.Responses.Pattern[1] // 2xx pattern
}

func successStreamType(op *ir.Operation) *ir.Type {
	r := successIRResponse(op)
	if r == nil {
		return nil
	}
	for _, media := range r.Contents {
		if media.Type != nil && media.Type.Is(ir.KindStream) {
			return media.Type
		}
	}
	return nil
}

// genNewError maps gRPC status codes/messages/details onto the ogen error type.
func (a *adapterGen) genNewError(gen *ogengen.Generator) {
	errType := ogenErrorType(gen)
	a.gf.P("// NewError converts a gRPC error into the ogen error response.")
	a.gf.P("func (a *OgenAdapter) NewError(ctx ", a.qual(protogen.GoIdent{GoName: "Context", GoImportPath: "context"}), ", err error) *", a.oid("ErrorStatusCode"), " {")
	a.gf.P("st := ", a.qual(protogen.GoIdent{GoName: "Status", GoImportPath: grpcbridgeImport}), "(err)")
	a.gf.P("e := ", a.oid("Error"), "{}")
	if errType != nil {
		for _, f := range errType.Fields {
			switch f.Tag.JSON {
			case "code":
				a.gf.P("e.", f.Name, " = st.Code().String()")
			case "message":
				a.gf.P("e.", f.Name, " = st.Message()")
			case "details":
				if f.Type.Is(ir.KindArray) {
					a.gf.P("e.", f.Name, " = ", a.qual(protogen.GoIdent{GoName: "Details", GoImportPath: grpcbridgeImport}), "(st)")
				}
			}
		}
	}
	a.gf.P("return &", a.oid("ErrorStatusCode"), "{")
	a.gf.P("StatusCode: ", a.qual(protogen.GoIdent{GoName: "HTTPStatus", GoImportPath: grpcbridgeImport}), "(st.Code()),")
	a.gf.P("Response: e,")
	a.gf.P("}")
	a.gf.P("}")
	a.gf.P()
}

// reqRespGoType mirrors ogen: pointer for pass-by-pointer types.
func (a *adapterGen) reqGoType(t *ir.Type) string {
	if t.DoPassByPointer() {
		return "*" + a.goType(t)
	}
	return a.goType(t)
}

func (a *adapterGen) mdString(t *ir.Type, src string) string {
	switch {
	case externalImports[t.Go()] != "":
		return src + ".String()"
	case t.Is(ir.KindPrimitive) && t.Go() == "string":
		return src
	default:
		return a.qual(protogen.GoIdent{GoName: "Sprint", GoImportPath: "fmt"}) + "(" + src + ")"
	}
}

func operationID(svc *protogen.Service, m *protogen.Method, opts *ogen.MethodOptions) string {
	return firstNonEmpty(opts.GetOperationId(), lowerFirst(string(svc.Desc.Name()))+string(m.Desc.Name()))
}

func parameterName(binding *ogen.ParameterBinding, field *protogen.Field) string {
	if binding.GetName() != "" {
		return binding.GetName()
	}
	if field != nil {
		return jsonName(field)
	}
	return binding.GetFieldPath()
}

func successFieldPath(opts *ogen.MethodOptions) string {
	for _, r := range opts.GetResponses() {
		if r.GetStatus() >= 200 && r.GetStatus() < 300 {
			return r.GetFieldPath()
		}
	}
	return ""
}

// ogenErrorType returns the ogen type used as ErrorStatusCode.Response.
func ogenErrorType(gen *ogengen.Generator) *ir.Type {
	for _, t := range gen.Types() {
		if t.Name != "ErrorStatusCode" {
			continue
		}
		for _, f := range t.Fields {
			if f.Name == "Response" {
				return f.Type
			}
		}
	}
	return nil
}

func strconvQuote(s string) string { return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"` }
