package generator

import (
	"fmt"
	"path"
	"sort"
	"strings"

	"github.com/gopherex/protoc-gen-go-ogen/ogen"
	ogengen "github.com/ogen-go/ogen/gen"
	"github.com/ogen-go/ogen/gen/ir"
	"google.golang.org/protobuf/compiler/protogen"
)

// External Go types that ogen uses for string formats.
var externalImports = map[string]protogen.GoImportPath{
	"uuid.UUID":     "github.com/google/uuid",
	"url.URL":       "net/url",
	"netip.Addr":    "net/netip",
	"time.Time":     "time",
	"time.Duration": "time",
}

const (
	wktTimestamp = "google.protobuf.Timestamp"
	wktDuration  = "google.protobuf.Duration"
	wktFieldMask = "google.protobuf.FieldMask"
)

// wktJSON maps the free-form JSON well-known types to the convert helper suffix
// used to bridge them (proto message <-> jx.Raw via protojson).
var wktJSON = map[string]string{
	"google.protobuf.Struct":    "Struct",
	"google.protobuf.Value":     "Value",
	"google.protobuf.ListValue": "ListValue",
	"google.protobuf.Any":       "Any",
}

var wktWrappers = map[string]bool{
	"google.protobuf.StringValue": true,
	"google.protobuf.Int32Value":  true,
	"google.protobuf.Int64Value":  true,
	"google.protobuf.UInt32Value": true,
	"google.protobuf.UInt64Value": true,
	"google.protobuf.FloatValue":  true,
	"google.protobuf.DoubleValue": true,
	"google.protobuf.BoolValue":   true,
	"google.protobuf.BytesValue":  true,
}

// convGen renders proto <-> ogen converters into a single Go file.
type convGen struct {
	gf         *protogen.GeneratedFile
	ogenImport protogen.GoImportPath
	structs    map[string]*ir.Type
	tmp        int
	// fail is the value returned alongside err on a conversion error. It is
	// "dst"/"nil" at function scope and the named zero return inside closures.
	fail string
}

// failLine emits a `return <fail>, err` statement for the current scope.
func (c *convGen) failLine() {
	c.gf.P("return ", c.fail, ", err")
}

// generateConverters emits proto<->ogen converters for every proto message that
// has a matching ogen component struct, reusing the ogen IR for exact Go names.
func (g *OpenAPIGenerator) generateConverters(file *protogen.File, fileOpts *ogen.FileOptions, gen *ogengen.Generator, fakerEnabled bool) error {
	msgByName := map[string]*protogen.Message{}
	var collect func(msgs []*protogen.Message)
	collect = func(msgs []*protogen.Message) {
		for _, m := range msgs {
			if name := g.componentName[m.Desc.FullName()]; name != "" {
				msgByName[name] = m
			}
			collect(m.Messages)
		}
	}
	collect(file.Messages)

	// Correlate ogen struct types to OpenAPI component names via their schema
	// ref, because ogen may rename the Go type (e.g. CoveragePayload -> Coverage).
	structs := map[string]*ir.Type{}
	for _, t := range gen.Types() {
		if t.Is(ir.KindStruct) && t.Schema != nil && t.Schema.Ref.Ptr != "" {
			structs[path.Base(t.Schema.Ref.Ptr)] = t
		}
	}

	var names []string
	for name := range msgByName {
		if _, ok := structs[name]; ok {
			names = append(names, name)
		}
	}
	if len(names) == 0 {
		return nil
	}
	sort.Strings(names)

	// Converters are emitted into the protoc-gen-go package (same dir as the
	// .pb.go), so ToOgen can be a method on the protobuf struct.
	pkgName := string(file.GoPackageName)
	gf := g.Plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".converters.go", file.GoImportPath)
	gf.P("// Code generated by protoc-gen-ogen. DO NOT EDIT.")
	gf.P()
	gf.P("package ", pkgName)
	gf.P()

	ogenImport := protogen.GoImportPath(fileOpts.GetOgenPackage())
	c := &convGen{
		gf:         gf,
		ogenImport: ogenImport,
		structs:    structs,
	}
	for _, name := range names {
		c.genMessage(msgByName[name], structs[name])
	}

	if fakerEnabled {
		g.generateConvertersTest(file, pkgName, ogenImport, names, msgByName, structs)
	}
	return nil
}

// generateConvertersTest emits a faker round-trip test per message into the
// protobuf package: SetFake -> FromOgen -> ToOgen -> FromOgen, then proto.Equal
// of the two protobuf values (a stable fixpoint even when some fields are lossy).
// Only emitted when ogen's faker (debug/example_tests) is enabled.
func (g *OpenAPIGenerator) generateConvertersTest(file *protogen.File, pkgName string, ogenImport protogen.GoImportPath, names []string, msgByName map[string]*protogen.Message, structs map[string]*ir.Type) {
	gf := g.Plugin.NewGeneratedFile(file.GeneratedFilenamePrefix+".converters_test.go", file.GoImportPath)
	testingT := protogen.GoIdent{GoName: "T", GoImportPath: "testing"}
	protoEqual := protogen.GoIdent{GoName: "Equal", GoImportPath: "google.golang.org/protobuf/proto"}
	gf.P("// Code generated by protoc-gen-ogen. DO NOT EDIT.")
	gf.P()
	gf.P("package ", pkgName)
	gf.P()
	for _, name := range names {
		// ogen does not generate a faker for types with multipart file fields.
		if ogenHasMultipart(structs[name]) {
			continue
		}
		msg := msgByName[name]
		oid := protogen.GoIdent{GoName: structs[name].Name, GoImportPath: ogenImport}
		fn := msg.GoIdent.GoName
		gf.P("func Test", fn, "OgenRoundTrip(t *", testingT, ") {")
		gf.P("var o ", oid)
		gf.P("o.SetFake()")
		gf.P("a, err := ", fn, "FromOgen(&o)")
		gf.P("if err != nil {")
		gf.P("t.Fatalf(\"", fn, "FromOgen: %v\", err)")
		gf.P("}")
		gf.P("oa, err := a.ToOgen()")
		gf.P("if err != nil {")
		gf.P("t.Fatalf(\"", fn, ".ToOgen: %v\", err)")
		gf.P("}")
		gf.P("b, err := ", fn, "FromOgen(oa)")
		gf.P("if err != nil {")
		gf.P("t.Fatalf(\"", fn, "FromOgen (2nd): %v\", err)")
		gf.P("}")
		gf.P("if !", protoEqual, "(a, b) {")
		gf.P("t.Fatalf(\"", fn, " round-trip mismatch:\\n a: %v\\n b: %v\", a, b)")
		gf.P("}")
		gf.P("}")
		gf.P()
	}
}

func (c *convGen) oid(name string) protogen.GoIdent {
	return protogen.GoIdent{GoName: name, GoImportPath: c.ogenImport}
}

func (c *convGen) ext(goType string) protogen.GoIdent {
	name := goType[strings.IndexByte(goType, '.')+1:]
	return protogen.GoIdent{GoName: name, GoImportPath: externalImports[goType]}
}

func (c *convGen) newTmp(prefix string) string {
	c.tmp++
	return fmt.Sprintf("%s%d", prefix, c.tmp)
}

// ogenHasMultipart reports whether a struct has any multipart file field, for
// which ogen does not generate a faker.
func ogenHasMultipart(ot *ir.Type) bool {
	for _, f := range ot.Fields {
		if strings.Contains(f.Type.Go(), "MultipartFile") {
			return true
		}
	}
	return false
}

// ogenFields maps a struct's JSON property name to its ir.Field.
func ogenFields(t *ir.Type) map[string]*ir.Field {
	out := map[string]*ir.Field{}
	for _, f := range t.Fields {
		if f.Tag.JSON != "" {
			out[f.Tag.JSON] = f
		}
	}
	return out
}

func (c *convGen) genMessage(msg *protogen.Message, ot *ir.Type) {
	fields := ogenFields(ot)
	c.tmp = 0
	c.genToOgen(msg, ot, fields)
	c.tmp = 0
	c.genFromOgen(msg, ot, fields)
}

// goType renders the Go type expression for an ogen ir.Type within the converter file.
func (c *convGen) goType(t *ir.Type) string {
	switch {
	case t.Go() == "jx.Raw":
		return c.gf.QualifiedGoIdent(protogen.GoIdent{GoName: "Raw", GoImportPath: "github.com/go-faster/jx"})
	case isMultipart(t):
		return c.gf.QualifiedGoIdent(protogen.GoIdent{GoName: "MultipartFile", GoImportPath: "github.com/ogen-go/ogen/http"})
	case externalImports[t.Go()] != "":
		return c.gf.QualifiedGoIdent(c.ext(t.Go()))
	case t.Is(ir.KindArray):
		return "[]" + c.goType(t.Item)
	case t.Is(ir.KindMap):
		return "map[string]" + c.goType(t.Item)
	case t.Name != "":
		return c.gf.QualifiedGoIdent(c.oid(t.Name))
	case t.Is(ir.KindPrimitive):
		return t.Primitive.String()
	default:
		return "any"
	}
}

func (c *convGen) genToOgen(msg *protogen.Message, ot *ir.Type, fields map[string]*ir.Field) {
	c.fail = "nil"
	c.gf.P("// ToOgen converts ", msg.GoIdent.GoName, " to its ogen representation.")
	c.gf.P("func (src *", msg.GoIdent, ") ToOgen() (*", c.oid(ot.Name), ", error) {")
	c.gf.P("var dst ", c.oid(ot.Name))
	c.gf.P("if src == nil {")
	c.gf.P("return &dst, nil")
	c.gf.P("}")
	for _, pf := range msg.Fields {
		if pf.Oneof != nil && !pf.Oneof.Desc.IsSynthetic() {
			continue
		}
		of := fields[fieldOpenAPIName(pf)]
		if of == nil {
			continue
		}
		c.toOgenField(pf, of)
	}
	for _, oneof := range msg.Oneofs {
		if oneof.Desc.IsSynthetic() {
			continue
		}
		if oneofMode(oneof) == ogen.OneofSchemaMode_ONEOF_SCHEMA_MODE_OBJECT {
			c.toOgenOneofObject(oneof, fields)
			continue
		}
		of := fields[string(oneof.Desc.Name())]
		if of == nil {
			continue
		}
		c.toOgenOneof(oneof, of)
	}
	c.gf.P("return &dst, nil")
	c.gf.P("}")
	c.gf.P()
}

func (c *convGen) genFromOgen(msg *protogen.Message, ot *ir.Type, fields map[string]*ir.Field) {
	c.fail = "nil"
	c.gf.P("// ", msg.GoIdent.GoName, "FromOgen converts the ogen representation back to ", msg.GoIdent.GoName, ".")
	c.gf.P("func ", msg.GoIdent.GoName, "FromOgen(src *", c.oid(ot.Name), ") (*", msg.GoIdent, ", error) {")
	c.gf.P("if src == nil {")
	c.gf.P("return nil, nil")
	c.gf.P("}")
	c.gf.P("dst := &", msg.GoIdent, "{}")
	for _, pf := range msg.Fields {
		if pf.Oneof != nil && !pf.Oneof.Desc.IsSynthetic() {
			continue
		}
		of := fields[fieldOpenAPIName(pf)]
		if of == nil {
			continue
		}
		c.fromOgenField(pf, of)
	}
	for _, oneof := range msg.Oneofs {
		if oneof.Desc.IsSynthetic() {
			continue
		}
		if oneofMode(oneof) == ogen.OneofSchemaMode_ONEOF_SCHEMA_MODE_OBJECT {
			c.fromOgenOneofObject(oneof, fields)
			continue
		}
		of := fields[string(oneof.Desc.Name())]
		if of == nil {
			continue
		}
		c.fromOgenOneof(oneof, of)
	}
	c.gf.P("return dst, nil")
	c.gf.P("}")
	c.gf.P()
}
