// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v0.14.1-v0.16.6-bufbuild-protocompile-easyp
// source: ogen/ogen.proto

package ogen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HTTP method for an OpenAPI operation.
// This cannot be inferred from a protobuf method.
type HttpMethod int32

const (
	HttpMethod_HTTP_METHOD_UNSPECIFIED HttpMethod = 0
	HttpMethod_HTTP_METHOD_GET         HttpMethod = 1
	HttpMethod_HTTP_METHOD_POST        HttpMethod = 2
	HttpMethod_HTTP_METHOD_PUT         HttpMethod = 3
	HttpMethod_HTTP_METHOD_PATCH       HttpMethod = 4
	HttpMethod_HTTP_METHOD_DELETE      HttpMethod = 5
	HttpMethod_HTTP_METHOD_HEAD        HttpMethod = 6
	HttpMethod_HTTP_METHOD_OPTIONS     HttpMethod = 7
	HttpMethod_HTTP_METHOD_TRACE       HttpMethod = 8
)

// Enum value maps for HttpMethod.
var (
	HttpMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "HTTP_METHOD_GET",
		2: "HTTP_METHOD_POST",
		3: "HTTP_METHOD_PUT",
		4: "HTTP_METHOD_PATCH",
		5: "HTTP_METHOD_DELETE",
		6: "HTTP_METHOD_HEAD",
		7: "HTTP_METHOD_OPTIONS",
		8: "HTTP_METHOD_TRACE",
	}
	HttpMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"HTTP_METHOD_GET":         1,
		"HTTP_METHOD_POST":        2,
		"HTTP_METHOD_PUT":         3,
		"HTTP_METHOD_PATCH":       4,
		"HTTP_METHOD_DELETE":      5,
		"HTTP_METHOD_HEAD":        6,
		"HTTP_METHOD_OPTIONS":     7,
		"HTTP_METHOD_TRACE":       8,
	}
)

func (x HttpMethod) Enum() *HttpMethod {
	p := new(HttpMethod)
	*p = x
	return p
}

func (x HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_ogen_ogen_proto_enumTypes[0].Descriptor()
}

func (HttpMethod) Type() protoreflect.EnumType {
	return &file_ogen_ogen_proto_enumTypes[0]
}

func (x HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HttpMethod.Descriptor instead.
func (HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{0}
}

// Location of a field when a protobuf request message is split into OpenAPI
// parameters and body.
type ParameterLocation int32

const (
	ParameterLocation_PARAMETER_LOCATION_UNSPECIFIED ParameterLocation = 0
	ParameterLocation_PARAMETER_LOCATION_PATH        ParameterLocation = 1
	ParameterLocation_PARAMETER_LOCATION_QUERY       ParameterLocation = 2
	ParameterLocation_PARAMETER_LOCATION_HEADER      ParameterLocation = 3
	ParameterLocation_PARAMETER_LOCATION_COOKIE      ParameterLocation = 4
)

// Enum value maps for ParameterLocation.
var (
	ParameterLocation_name = map[int32]string{
		0: "PARAMETER_LOCATION_UNSPECIFIED",
		1: "PARAMETER_LOCATION_PATH",
		2: "PARAMETER_LOCATION_QUERY",
		3: "PARAMETER_LOCATION_HEADER",
		4: "PARAMETER_LOCATION_COOKIE",
	}
	ParameterLocation_value = map[string]int32{
		"PARAMETER_LOCATION_UNSPECIFIED": 0,
		"PARAMETER_LOCATION_PATH":        1,
		"PARAMETER_LOCATION_QUERY":       2,
		"PARAMETER_LOCATION_HEADER":      3,
		"PARAMETER_LOCATION_COOKIE":      4,
	}
)

func (x ParameterLocation) Enum() *ParameterLocation {
	p := new(ParameterLocation)
	*p = x
	return p
}

func (x ParameterLocation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParameterLocation) Descriptor() protoreflect.EnumDescriptor {
	return file_ogen_ogen_proto_enumTypes[1].Descriptor()
}

func (ParameterLocation) Type() protoreflect.EnumType {
	return &file_ogen_ogen_proto_enumTypes[1]
}

func (x ParameterLocation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParameterLocation.Descriptor instead.
func (ParameterLocation) EnumDescriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{1}
}

// String formats supported by ogen in addition to the protobuf type system.
// Basic OpenAPI type is inferred from the field kind; set this only when the
// protobuf scalar does not carry enough meaning.
type StringFormat int32

const (
	StringFormat_STRING_FORMAT_UNSPECIFIED  StringFormat = 0
	StringFormat_STRING_FORMAT_BYTE         StringFormat = 1
	StringFormat_STRING_FORMAT_BINARY       StringFormat = 2
	StringFormat_STRING_FORMAT_DATE         StringFormat = 3
	StringFormat_STRING_FORMAT_DATE_TIME    StringFormat = 4
	StringFormat_STRING_FORMAT_TIME         StringFormat = 5
	StringFormat_STRING_FORMAT_DURATION     StringFormat = 6
	StringFormat_STRING_FORMAT_UUID         StringFormat = 7
	StringFormat_STRING_FORMAT_IP           StringFormat = 8
	StringFormat_STRING_FORMAT_IPV4         StringFormat = 9
	StringFormat_STRING_FORMAT_IPV6         StringFormat = 10
	StringFormat_STRING_FORMAT_URI          StringFormat = 11
	StringFormat_STRING_FORMAT_EMAIL        StringFormat = 12
	StringFormat_STRING_FORMAT_HOSTNAME     StringFormat = 13
	StringFormat_STRING_FORMAT_UNIX         StringFormat = 14
	StringFormat_STRING_FORMAT_UNIX_SECONDS StringFormat = 15
	StringFormat_STRING_FORMAT_UNIX_MILLI   StringFormat = 16
	StringFormat_STRING_FORMAT_UNIX_MICRO   StringFormat = 17
	StringFormat_STRING_FORMAT_UNIX_NANO    StringFormat = 18
	StringFormat_STRING_FORMAT_INT32        StringFormat = 19
	StringFormat_STRING_FORMAT_INT64        StringFormat = 20
)

// Enum value maps for StringFormat.
var (
	StringFormat_name = map[int32]string{
		0:  "STRING_FORMAT_UNSPECIFIED",
		1:  "STRING_FORMAT_BYTE",
		2:  "STRING_FORMAT_BINARY",
		3:  "STRING_FORMAT_DATE",
		4:  "STRING_FORMAT_DATE_TIME",
		5:  "STRING_FORMAT_TIME",
		6:  "STRING_FORMAT_DURATION",
		7:  "STRING_FORMAT_UUID",
		8:  "STRING_FORMAT_IP",
		9:  "STRING_FORMAT_IPV4",
		10: "STRING_FORMAT_IPV6",
		11: "STRING_FORMAT_URI",
		12: "STRING_FORMAT_EMAIL",
		13: "STRING_FORMAT_HOSTNAME",
		14: "STRING_FORMAT_UNIX",
		15: "STRING_FORMAT_UNIX_SECONDS",
		16: "STRING_FORMAT_UNIX_MILLI",
		17: "STRING_FORMAT_UNIX_MICRO",
		18: "STRING_FORMAT_UNIX_NANO",
		19: "STRING_FORMAT_INT32",
		20: "STRING_FORMAT_INT64",
	}
	StringFormat_value = map[string]int32{
		"STRING_FORMAT_UNSPECIFIED":  0,
		"STRING_FORMAT_BYTE":         1,
		"STRING_FORMAT_BINARY":       2,
		"STRING_FORMAT_DATE":         3,
		"STRING_FORMAT_DATE_TIME":    4,
		"STRING_FORMAT_TIME":         5,
		"STRING_FORMAT_DURATION":     6,
		"STRING_FORMAT_UUID":         7,
		"STRING_FORMAT_IP":           8,
		"STRING_FORMAT_IPV4":         9,
		"STRING_FORMAT_IPV6":         10,
		"STRING_FORMAT_URI":          11,
		"STRING_FORMAT_EMAIL":        12,
		"STRING_FORMAT_HOSTNAME":     13,
		"STRING_FORMAT_UNIX":         14,
		"STRING_FORMAT_UNIX_SECONDS": 15,
		"STRING_FORMAT_UNIX_MILLI":   16,
		"STRING_FORMAT_UNIX_MICRO":   17,
		"STRING_FORMAT_UNIX_NANO":    18,
		"STRING_FORMAT_INT32":        19,
		"STRING_FORMAT_INT64":        20,
	}
)

func (x StringFormat) Enum() *StringFormat {
	p := new(StringFormat)
	*p = x
	return p
}

func (x StringFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StringFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_ogen_ogen_proto_enumTypes[2].Descriptor()
}

func (StringFormat) Type() protoreflect.EnumType {
	return &file_ogen_ogen_proto_enumTypes[2]
}

func (x StringFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StringFormat.Descriptor instead.
func (StringFormat) EnumDescriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{2}
}

// How a protobuf oneof is represented in OpenAPI.
// Default should be oneOf, but object/discriminator mode is useful for APIs
// that expose tagged unions explicitly.
type OneofSchemaMode int32

const (
	OneofSchemaMode_ONEOF_SCHEMA_MODE_UNSPECIFIED OneofSchemaMode = 0
	OneofSchemaMode_ONEOF_SCHEMA_MODE_ONE_OF      OneofSchemaMode = 1
	OneofSchemaMode_ONEOF_SCHEMA_MODE_ANY_OF      OneofSchemaMode = 2
	OneofSchemaMode_ONEOF_SCHEMA_MODE_OBJECT      OneofSchemaMode = 3
)

// Enum value maps for OneofSchemaMode.
var (
	OneofSchemaMode_name = map[int32]string{
		0: "ONEOF_SCHEMA_MODE_UNSPECIFIED",
		1: "ONEOF_SCHEMA_MODE_ONE_OF",
		2: "ONEOF_SCHEMA_MODE_ANY_OF",
		3: "ONEOF_SCHEMA_MODE_OBJECT",
	}
	OneofSchemaMode_value = map[string]int32{
		"ONEOF_SCHEMA_MODE_UNSPECIFIED": 0,
		"ONEOF_SCHEMA_MODE_ONE_OF":      1,
		"ONEOF_SCHEMA_MODE_ANY_OF":      2,
		"ONEOF_SCHEMA_MODE_OBJECT":      3,
	}
)

func (x OneofSchemaMode) Enum() *OneofSchemaMode {
	p := new(OneofSchemaMode)
	*p = x
	return p
}

func (x OneofSchemaMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OneofSchemaMode) Descriptor() protoreflect.EnumDescriptor {
	return file_ogen_ogen_proto_enumTypes[3].Descriptor()
}

func (OneofSchemaMode) Type() protoreflect.EnumType {
	return &file_ogen_ogen_proto_enumTypes[3]
}

func (x OneofSchemaMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OneofSchemaMode.Descriptor instead.
func (OneofSchemaMode) EnumDescriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{3}
}

// Generic OpenAPI string pair, mostly for x-* extensions and discriminator maps.
type NamedString struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenAPI key or extension name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Raw string value for the key.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamedString) Reset() {
	*x = NamedString{}
	mi := &file_ogen_ogen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamedString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamedString) ProtoMessage() {}

func (x *NamedString) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamedString.ProtoReflect.Descriptor instead.
func (*NamedString) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{0}
}

func (x *NamedString) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamedString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// OpenAPI Server Object.
type Server struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server URL. Not derivable from protobuf.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional human-readable description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// OpenAPI x-* extensions, for example x-ogen-server-name.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_ogen_ogen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{1}
}

func (x *Server) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Server) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Server) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// OpenAPI External Documentation Object.
type ExternalDocs struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Documentation URL.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Optional human-readable description.
	Description   string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalDocs) Reset() {
	*x = ExternalDocs{}
	mi := &file_ogen_ogen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalDocs) ProtoMessage() {}

func (x *ExternalDocs) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalDocs.ProtoReflect.Descriptor instead.
func (*ExternalDocs) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalDocs) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ExternalDocs) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// OpenAPI Contact Object.
type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_ogen_ogen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{3}
}

func (x *Contact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Contact) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Contact) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// OpenAPI License Object.
type License struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *License) Reset() {
	*x = License{}
	mi := &file_ogen_ogen_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *License) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*License) ProtoMessage() {}

func (x *License) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use License.ProtoReflect.Descriptor instead.
func (*License) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{4}
}

func (x *License) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *License) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// OpenAPI Tag Object.
type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ExternalDocs  *ExternalDocs          `protobuf:"bytes,3,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_ogen_ogen_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{5}
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tag) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

// Go identifier used by converter generation when the inferred ogen type is
// not the desired target type.
type GoIdent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImportPath    string                 `protobuf:"bytes,2,opt,name=import_path,json=importPath,proto3" json:"import_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoIdent) Reset() {
	*x = GoIdent{}
	mi := &file_ogen_ogen_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoIdent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoIdent) ProtoMessage() {}

func (x *GoIdent) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoIdent.ProtoReflect.Descriptor instead.
func (*GoIdent) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{6}
}

func (x *GoIdent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoIdent) GetImportPath() string {
	if x != nil {
		return x.ImportPath
	}
	return ""
}

// Reference to an existing OpenAPI schema, usually "#/components/schemas/Foo".
type SchemaRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ref           string                 `protobuf:"bytes,1,opt,name=ref,proto3" json:"ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaRef) Reset() {
	*x = SchemaRef{}
	mi := &file_ogen_ogen_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaRef) ProtoMessage() {}

func (x *SchemaRef) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaRef.ProtoReflect.Descriptor instead.
func (*SchemaRef) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{7}
}

func (x *SchemaRef) GetRef() string {
	if x != nil {
		return x.Ref
	}
	return ""
}

// Schema overrides and metadata.
// The generator should infer OpenAPI type/format from protobuf descriptors:
// scalar kind, map/repeated cardinality, enum, message, well-known types, and
// field presence. Validation constraints are intentionally not duplicated here:
// generator code should read supported validation extensions, such as PGV, from
// descriptors and translate them to OpenAPI schema constraints.
type SchemaOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenAPI title override. Empty means derive from message/field name.
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// OpenAPI description override. Empty means use protobuf source comments.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// OpenAPI default value as raw JSON.
	DefaultJson string `protobuf:"bytes,3,opt,name=default_json,json=defaultJson,proto3" json:"default_json,omitempty"`
	// OpenAPI examples as raw JSON values.
	ExamplesJson []string `protobuf:"bytes,4,rep,name=examples_json,json=examplesJson,proto3" json:"examples_json,omitempty"`
	// OpenAPI enum values as raw JSON. Mostly useful for string enums.
	EnumJson []string `protobuf:"bytes,5,rep,name=enum_json,json=enumJson,proto3" json:"enum_json,omitempty"`
	// String format override. Numeric formats are derived from protobuf scalar
	// kind, while string semantics like uuid/email/date need an explicit hint.
	StringFormat StringFormat `protobuf:"varint,10,opt,name=string_format,json=stringFormat,proto3,enum=ogen.StringFormat" json:"string_format,omitempty"`
	// Custom OpenAPI format when StringFormat is not enough.
	CustomFormat string `protobuf:"bytes,11,opt,name=custom_format,json=customFormat,proto3" json:"custom_format,omitempty"`
	// Nullable override. If unset, infer from protobuf presence/wrapper/message
	// rules and method/body context.
	Nullable *bool `protobuf:"varint,20,opt,name=nullable,proto3,oneof" json:"nullable,omitempty"`
	// OpenAPI readOnly flag. Not expressible in protobuf.
	ReadOnly *bool `protobuf:"varint,21,opt,name=read_only,json=readOnly,proto3,oneof" json:"read_only,omitempty"`
	// OpenAPI writeOnly flag. Not expressible in protobuf.
	WriteOnly *bool `protobuf:"varint,22,opt,name=write_only,json=writeOnly,proto3,oneof" json:"write_only,omitempty"`
	// OpenAPI x-* extensions.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchemaOptions) Reset() {
	*x = SchemaOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchemaOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchemaOptions) ProtoMessage() {}

func (x *SchemaOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchemaOptions.ProtoReflect.Descriptor instead.
func (*SchemaOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{8}
}

func (x *SchemaOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SchemaOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SchemaOptions) GetDefaultJson() string {
	if x != nil {
		return x.DefaultJson
	}
	return ""
}

func (x *SchemaOptions) GetExamplesJson() []string {
	if x != nil {
		return x.ExamplesJson
	}
	return nil
}

func (x *SchemaOptions) GetEnumJson() []string {
	if x != nil {
		return x.EnumJson
	}
	return nil
}

func (x *SchemaOptions) GetStringFormat() StringFormat {
	if x != nil {
		return x.StringFormat
	}
	return StringFormat_STRING_FORMAT_UNSPECIFIED
}

func (x *SchemaOptions) GetCustomFormat() string {
	if x != nil {
		return x.CustomFormat
	}
	return ""
}

func (x *SchemaOptions) GetNullable() bool {
	if x != nil && x.Nullable != nil {
		return *x.Nullable
	}
	return false
}

func (x *SchemaOptions) GetReadOnly() bool {
	if x != nil && x.ReadOnly != nil {
		return *x.ReadOnly
	}
	return false
}

func (x *SchemaOptions) GetWriteOnly() bool {
	if x != nil && x.WriteOnly != nil {
		return *x.WriteOnly
	}
	return false
}

func (x *SchemaOptions) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// File-level generation and OpenAPI document options.
type FileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Generate openapi.yaml for this protobuf file.
	GenerateOpenapi bool `protobuf:"varint,1,opt,name=generate_openapi,json=generateOpenapi,proto3" json:"generate_openapi,omitempty"`
	// Generate or invoke ogen codegen from the generated openapi.yaml.
	GenerateOgen bool `protobuf:"varint,2,opt,name=generate_ogen,json=generateOgen,proto3" json:"generate_ogen,omitempty"`
	// Generate proto <-> ogen converters.
	GenerateConverters bool `protobuf:"varint,3,opt,name=generate_converters,json=generateConverters,proto3" json:"generate_converters,omitempty"`
	// OpenAPI version. Empty means generator default, normally "3.1.0" or "3.0.3".
	OpenapiVersion string `protobuf:"bytes,10,opt,name=openapi_version,json=openapiVersion,proto3" json:"openapi_version,omitempty"`
	// OpenAPI Info.title. Empty means derive from protobuf package/file name.
	Title string `protobuf:"bytes,11,opt,name=title,proto3" json:"title,omitempty"`
	// OpenAPI Info.version. Not derivable from protobuf, default should be "0.0.0".
	Version string `protobuf:"bytes,12,opt,name=version,proto3" json:"version,omitempty"`
	// OpenAPI Info.summary override.
	Summary string `protobuf:"bytes,13,opt,name=summary,proto3" json:"summary,omitempty"`
	// OpenAPI Info.description override. Empty means use file comments if present.
	Description string `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	// OpenAPI Info.termsOfService.
	TermsOfService string        `protobuf:"bytes,15,opt,name=terms_of_service,json=termsOfService,proto3" json:"terms_of_service,omitempty"`
	Contact        *Contact      `protobuf:"bytes,16,opt,name=contact,proto3" json:"contact,omitempty"`
	License        *License      `protobuf:"bytes,17,opt,name=license,proto3" json:"license,omitempty"`
	Servers        []*Server     `protobuf:"bytes,18,rep,name=servers,proto3" json:"servers,omitempty"`
	Tags           []*Tag        `protobuf:"bytes,19,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalDocs   *ExternalDocs `protobuf:"bytes,20,opt,name=external_docs,json=externalDocs,proto3" json:"external_docs,omitempty"`
	// Path for generated OpenAPI file. Empty means next to the input proto.
	OpenapiOutput string `protobuf:"bytes,30,opt,name=openapi_output,json=openapiOutput,proto3" json:"openapi_output,omitempty"`
	// Ogen target directory. Empty means generator default.
	OgenTarget string `protobuf:"bytes,31,opt,name=ogen_target,json=ogenTarget,proto3" json:"ogen_target,omitempty"`
	// Go package path for generated ogen code. Empty means infer from ogen_target.
	OgenPackage string `protobuf:"bytes,32,opt,name=ogen_package,json=ogenPackage,proto3" json:"ogen_package,omitempty"`
	// Short Go package name for generated ogen code (the ogen --package flag).
	// Empty means use the last path segment of ogen_package, then ogen_target.
	OgenPackageName string `protobuf:"bytes,34,opt,name=ogen_package_name,json=ogenPackageName,proto3" json:"ogen_package_name,omitempty"`
	// OpenAPI x-* extensions.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{9}
}

func (x *FileOptions) GetGenerateOpenapi() bool {
	if x != nil {
		return x.GenerateOpenapi
	}
	return false
}

func (x *FileOptions) GetGenerateOgen() bool {
	if x != nil {
		return x.GenerateOgen
	}
	return false
}

func (x *FileOptions) GetGenerateConverters() bool {
	if x != nil {
		return x.GenerateConverters
	}
	return false
}

func (x *FileOptions) GetOpenapiVersion() string {
	if x != nil {
		return x.OpenapiVersion
	}
	return ""
}

func (x *FileOptions) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *FileOptions) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *FileOptions) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *FileOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FileOptions) GetTermsOfService() string {
	if x != nil {
		return x.TermsOfService
	}
	return ""
}

func (x *FileOptions) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *FileOptions) GetLicense() *License {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *FileOptions) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *FileOptions) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *FileOptions) GetExternalDocs() *ExternalDocs {
	if x != nil {
		return x.ExternalDocs
	}
	return nil
}

func (x *FileOptions) GetOpenapiOutput() string {
	if x != nil {
		return x.OpenapiOutput
	}
	return ""
}

func (x *FileOptions) GetOgenTarget() string {
	if x != nil {
		return x.OgenTarget
	}
	return ""
}

func (x *FileOptions) GetOgenPackage() string {
	if x != nil {
		return x.OgenPackage
	}
	return ""
}

func (x *FileOptions) GetOgenPackageName() string {
	if x != nil {
		return x.OgenPackageName
	}
	return ""
}

func (x *FileOptions) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Message-level schema and converter options.
type MessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exclude this message from OpenAPI components and converter generation.
	// By default, messages reachable from services should be generated.
	Omit bool `protobuf:"varint,1,opt,name=omit,proto3" json:"omit,omitempty"`
	// Override component schema name. Empty means derive from protobuf full name.
	SchemaName string `protobuf:"bytes,2,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// Schema metadata overrides.
	Schema *SchemaOptions `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// Override the generated ogen Go type used by converters.
	OverrideOgenType *GoIdent `protobuf:"bytes,10,opt,name=override_ogen_type,json=overrideOgenType,proto3" json:"override_ogen_type,omitempty"`
	// Whether object schemas allow unknown JSON properties.
	// If unset in implementation, default should be false for protobuf messages.
	AdditionalProperties *bool `protobuf:"varint,20,opt,name=additional_properties,json=additionalProperties,proto3,oneof" json:"additional_properties,omitempty"`
	// Schema for unknown JSON properties when additional_properties is true.
	AdditionalPropertiesSchema *SchemaRef `protobuf:"bytes,21,opt,name=additional_properties_schema,json=additionalPropertiesSchema,proto3" json:"additional_properties_schema,omitempty"`
	// Discriminator property for polymorphic/object oneof schemas.
	DiscriminatorProperty string `protobuf:"bytes,22,opt,name=discriminator_property,json=discriminatorProperty,proto3" json:"discriminator_property,omitempty"`
	// Discriminator value -> schema ref/type name mapping.
	DiscriminatorMapping []*NamedString `protobuf:"bytes,23,rep,name=discriminator_mapping,json=discriminatorMapping,proto3" json:"discriminator_mapping,omitempty"`
	// OpenAPI x-* extensions.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{10}
}

func (x *MessageOptions) GetOmit() bool {
	if x != nil {
		return x.Omit
	}
	return false
}

func (x *MessageOptions) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *MessageOptions) GetSchema() *SchemaOptions {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *MessageOptions) GetOverrideOgenType() *GoIdent {
	if x != nil {
		return x.OverrideOgenType
	}
	return nil
}

func (x *MessageOptions) GetAdditionalProperties() bool {
	if x != nil && x.AdditionalProperties != nil {
		return *x.AdditionalProperties
	}
	return false
}

func (x *MessageOptions) GetAdditionalPropertiesSchema() *SchemaRef {
	if x != nil {
		return x.AdditionalPropertiesSchema
	}
	return nil
}

func (x *MessageOptions) GetDiscriminatorProperty() string {
	if x != nil {
		return x.DiscriminatorProperty
	}
	return ""
}

func (x *MessageOptions) GetDiscriminatorMapping() []*NamedString {
	if x != nil {
		return x.DiscriminatorMapping
	}
	return nil
}

func (x *MessageOptions) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Field-level schema and converter options.
type FieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exclude this field from generated OpenAPI schema and converters.
	Omit bool `protobuf:"varint,1,opt,name=omit,proto3" json:"omit,omitempty"`
	// Required override for OpenAPI object properties/parameters.
	// If unset, infer from proto2 required, proto3 optional, oneof, path params,
	// and chosen generator defaults.
	Required *bool `protobuf:"varint,2,opt,name=required,proto3,oneof" json:"required,omitempty"`
	// Override JSON/OpenAPI property or parameter name.
	// Empty means use protobuf json_name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Schema metadata overrides.
	Schema *SchemaOptions `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	// Override the generated ogen Go type used by converters.
	OverrideOgenType *GoIdent `protobuf:"bytes,10,opt,name=override_ogen_type,json=overrideOgenType,proto3" json:"override_ogen_type,omitempty"`
	// Represent enum values as strings in OpenAPI/JSON.
	EnumAsString bool `protobuf:"varint,11,opt,name=enum_as_string,json=enumAsString,proto3" json:"enum_as_string,omitempty"`
	// Represent enum values as integers in OpenAPI/JSON.
	EnumAsInt bool `protobuf:"varint,12,opt,name=enum_as_int,json=enumAsInt,proto3" json:"enum_as_int,omitempty"`
	// Override generated ogen Go struct field name via x-ogen-properties.
	GoName string `protobuf:"bytes,13,opt,name=go_name,json=goName,proto3" json:"go_name,omitempty"`
	// OpenAPI x-* extensions.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{11}
}

func (x *FieldOptions) GetOmit() bool {
	if x != nil {
		return x.Omit
	}
	return false
}

func (x *FieldOptions) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *FieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldOptions) GetSchema() *SchemaOptions {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *FieldOptions) GetOverrideOgenType() *GoIdent {
	if x != nil {
		return x.OverrideOgenType
	}
	return nil
}

func (x *FieldOptions) GetEnumAsString() bool {
	if x != nil {
		return x.EnumAsString
	}
	return false
}

func (x *FieldOptions) GetEnumAsInt() bool {
	if x != nil {
		return x.EnumAsInt
	}
	return false
}

func (x *FieldOptions) GetGoName() string {
	if x != nil {
		return x.GoName
	}
	return ""
}

func (x *FieldOptions) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Oneof-level schema options.
type OneofOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// OpenAPI representation of this protobuf oneof.
	SchemaMode OneofSchemaMode `protobuf:"varint,1,opt,name=schema_mode,json=schemaMode,proto3,enum=ogen.OneofSchemaMode" json:"schema_mode,omitempty"`
	// Discriminator property for object/tagged union representation.
	DiscriminatorProperty string `protobuf:"bytes,2,opt,name=discriminator_property,json=discriminatorProperty,proto3" json:"discriminator_property,omitempty"`
	// Discriminator value -> schema ref/type name mapping.
	DiscriminatorMapping []*NamedString `protobuf:"bytes,3,rep,name=discriminator_mapping,json=discriminatorMapping,proto3" json:"discriminator_mapping,omitempty"`
	// Schema metadata shared by the oneof schema.
	Schema        *SchemaOptions `protobuf:"bytes,4,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofOptions) Reset() {
	*x = OneofOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofOptions) ProtoMessage() {}

func (x *OneofOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofOptions.ProtoReflect.Descriptor instead.
func (*OneofOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{12}
}

func (x *OneofOptions) GetSchemaMode() OneofSchemaMode {
	if x != nil {
		return x.SchemaMode
	}
	return OneofSchemaMode_ONEOF_SCHEMA_MODE_UNSPECIFIED
}

func (x *OneofOptions) GetDiscriminatorProperty() string {
	if x != nil {
		return x.DiscriminatorProperty
	}
	return ""
}

func (x *OneofOptions) GetDiscriminatorMapping() []*NamedString {
	if x != nil {
		return x.DiscriminatorMapping
	}
	return nil
}

func (x *OneofOptions) GetSchema() *SchemaOptions {
	if x != nil {
		return x.Schema
	}
	return nil
}

// Service-level OpenAPI options.
type ServiceOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exclude this service from OpenAPI operation generation.
	// By default, services with annotated methods should be generated.
	Omit bool `protobuf:"varint,1,opt,name=omit,proto3" json:"omit,omitempty"`
	// Prefix prepended to method paths.
	PathPrefix string `protobuf:"bytes,2,opt,name=path_prefix,json=pathPrefix,proto3" json:"path_prefix,omitempty"`
	// Tags applied to all methods in this service. Empty means service name.
	Tags []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	// Description override. Empty means use protobuf source comments.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Servers applied to all methods in this service.
	Servers []*Server `protobuf:"bytes,5,rep,name=servers,proto3" json:"servers,omitempty"`
	// OpenAPI x-* extensions.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceOptions) Reset() {
	*x = ServiceOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceOptions) ProtoMessage() {}

func (x *ServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceOptions.ProtoReflect.Descriptor instead.
func (*ServiceOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{13}
}

func (x *ServiceOptions) GetOmit() bool {
	if x != nil {
		return x.Omit
	}
	return false
}

func (x *ServiceOptions) GetPathPrefix() string {
	if x != nil {
		return x.PathPrefix
	}
	return ""
}

func (x *ServiceOptions) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ServiceOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceOptions) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *ServiceOptions) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Request body binding for a protobuf method input.
type RequestBody struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Description override. Empty means use field/message comments.
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Required override for requestBody.required.
	Required bool `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	// Media type. Empty means "application/json".
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Dot-separated field path inside the protobuf request message.
	// Empty means the whole request message is the body.
	FieldPath string `protobuf:"bytes,4,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// OpenAPI x-* extensions for the media type object, for example
	// x-ogen-json-streaming.
	MediaExtensions []*NamedString `protobuf:"bytes,5,rep,name=media_extensions,json=mediaExtensions,proto3" json:"media_extensions,omitempty"`
	// OpenAPI x-* extensions for the requestBody object.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestBody) Reset() {
	*x = RequestBody{}
	mi := &file_ogen_ogen_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestBody) ProtoMessage() {}

func (x *RequestBody) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestBody.ProtoReflect.Descriptor instead.
func (*RequestBody) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{14}
}

func (x *RequestBody) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RequestBody) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *RequestBody) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *RequestBody) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *RequestBody) GetMediaExtensions() []*NamedString {
	if x != nil {
		return x.MediaExtensions
	}
	return nil
}

func (x *RequestBody) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// Response binding for a protobuf method output.
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code. Required for non-default responses.
	Status uint32 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// Description override. Empty means infer from status or comments.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Media type. Empty means "application/json" when a body is present.
	ContentType string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	// Dot-separated field path inside the protobuf response message.
	// Empty means the whole response message is the body.
	FieldPath string `protobuf:"bytes,4,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// Explicit schema reference when the response body is not represented by the
	// protobuf response message.
	Schema *SchemaRef `protobuf:"bytes,5,opt,name=schema,proto3" json:"schema,omitempty"`
	// Header name -> dot-separated response field path.
	Headers       []*NamedString `protobuf:"bytes,6,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_ogen_ogen_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{15}
}

func (x *Response) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Response) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Response) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *Response) GetSchema() *SchemaRef {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *Response) GetHeaders() []*NamedString {
	if x != nil {
		return x.Headers
	}
	return nil
}

// Parameter binding for a field inside a protobuf method input.
type ParameterBinding struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dot-separated field path inside the protobuf request message.
	FieldPath string `protobuf:"bytes,1,opt,name=field_path,json=fieldPath,proto3" json:"field_path,omitempty"`
	// OpenAPI parameter location.
	In ParameterLocation `protobuf:"varint,2,opt,name=in,proto3,enum=ogen.ParameterLocation" json:"in,omitempty"`
	// Parameter name. Empty means use field json_name or path template name.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Required override. Path parameters are always required.
	Required *bool `protobuf:"varint,4,opt,name=required,proto3,oneof" json:"required,omitempty"`
	// Description override. Empty means use field comments.
	Description string `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	// Schema metadata overrides.
	Schema *SchemaOptions `protobuf:"bytes,6,opt,name=schema,proto3" json:"schema,omitempty"`
	// OpenAPI parameter style. Empty means OpenAPI default for location.
	Style string `protobuf:"bytes,7,opt,name=style,proto3" json:"style,omitempty"`
	// OpenAPI parameter explode flag.
	Explode       *bool `protobuf:"varint,8,opt,name=explode,proto3,oneof" json:"explode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterBinding) Reset() {
	*x = ParameterBinding{}
	mi := &file_ogen_ogen_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterBinding) ProtoMessage() {}

func (x *ParameterBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterBinding.ProtoReflect.Descriptor instead.
func (*ParameterBinding) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{16}
}

func (x *ParameterBinding) GetFieldPath() string {
	if x != nil {
		return x.FieldPath
	}
	return ""
}

func (x *ParameterBinding) GetIn() ParameterLocation {
	if x != nil {
		return x.In
	}
	return ParameterLocation_PARAMETER_LOCATION_UNSPECIFIED
}

func (x *ParameterBinding) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterBinding) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

func (x *ParameterBinding) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ParameterBinding) GetSchema() *SchemaOptions {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ParameterBinding) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

func (x *ParameterBinding) GetExplode() bool {
	if x != nil && x.Explode != nil {
		return *x.Explode
	}
	return false
}

// OpenAPI webhook binding for a protobuf method.
// Webhooks are regular HTTP callback operations described in the top-level
// OpenAPI 3.1 "webhooks" object. They are not WebSocket/SSE streams.
type WebhookOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Webhook name under the top-level OpenAPI "webhooks" object.
	// Required when MethodOptions.webhook is set.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookOptions) Reset() {
	*x = WebhookOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookOptions) ProtoMessage() {}

func (x *WebhookOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookOptions.ProtoReflect.Descriptor instead.
func (*WebhookOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{17}
}

func (x *WebhookOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Method-level OpenAPI operation options.
type MethodOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Exclude this method from OpenAPI operation generation.
	Omit bool `protobuf:"varint,1,opt,name=omit,proto3" json:"omit,omitempty"`
	// HTTP method. Required to expose a protobuf method as HTTP.
	HttpMethod HttpMethod `protobuf:"varint,2,opt,name=http_method,json=httpMethod,proto3,enum=ogen.HttpMethod" json:"http_method,omitempty"`
	// HTTP path template, for example "/users/{id}".
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Operation ID override. Empty means derive from service and method names.
	OperationId string `protobuf:"bytes,4,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// Summary override. Empty means use protobuf leading comments first line.
	Summary string `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	// Description override. Empty means use protobuf leading comments.
	Description string `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	// Tags override. Empty means inherit service tags.
	Tags []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	// OpenAPI deprecated flag. Empty in proto is false; protobuf deprecated option
	// should also be honored by the generator.
	Deprecated bool `protobuf:"varint,8,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	// Put this method into top-level OpenAPI 3.1 webhooks instead of paths.
	Webhook *WebhookOptions `protobuf:"bytes,9,opt,name=webhook,proto3" json:"webhook,omitempty"`
	// Request body binding. Empty means no body, unless generator chooses a
	// method-based default.
	RequestBody *RequestBody `protobuf:"bytes,20,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	// Explicit parameter bindings. Path parameters can be inferred from path
	// template names when they match request fields; use this for query/header/
	// cookie params or custom names/styles.
	Parameters []*ParameterBinding `protobuf:"bytes,21,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// Response bindings. Empty should default to a 200 response with the whole
	// protobuf output message as JSON.
	Responses []*Response `protobuf:"bytes,22,rep,name=responses,proto3" json:"responses,omitempty"`
	// Operation-level servers.
	Servers []*Server `protobuf:"bytes,30,rep,name=servers,proto3" json:"servers,omitempty"`
	// OpenAPI x-* extensions.
	Extensions    []*NamedString `protobuf:"bytes,100,rep,name=extensions,proto3" json:"extensions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodOptions) Reset() {
	*x = MethodOptions{}
	mi := &file_ogen_ogen_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodOptions) ProtoMessage() {}

func (x *MethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_ogen_ogen_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodOptions.ProtoReflect.Descriptor instead.
func (*MethodOptions) Descriptor() ([]byte, []int) {
	return file_ogen_ogen_proto_rawDescGZIP(), []int{18}
}

func (x *MethodOptions) GetOmit() bool {
	if x != nil {
		return x.Omit
	}
	return false
}

func (x *MethodOptions) GetHttpMethod() HttpMethod {
	if x != nil {
		return x.HttpMethod
	}
	return HttpMethod_HTTP_METHOD_UNSPECIFIED
}

func (x *MethodOptions) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MethodOptions) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *MethodOptions) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MethodOptions) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MethodOptions) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MethodOptions) GetDeprecated() bool {
	if x != nil {
		return x.Deprecated
	}
	return false
}

func (x *MethodOptions) GetWebhook() *WebhookOptions {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *MethodOptions) GetRequestBody() *RequestBody {
	if x != nil {
		return x.RequestBody
	}
	return nil
}

func (x *MethodOptions) GetParameters() []*ParameterBinding {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *MethodOptions) GetResponses() []*Response {
	if x != nil {
		return x.Responses
	}
	return nil
}

func (x *MethodOptions) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *MethodOptions) GetExtensions() []*NamedString {
	if x != nil {
		return x.Extensions
	}
	return nil
}

var file_ogen_ogen_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         60030,
		Name:          "ogen.file",
		Tag:           "bytes,60030,opt,name=file",
		Filename:      "ogen/ogen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.EnumOptions)(nil),
		ExtensionType: (*SchemaOptions)(nil),
		Field:         60030,
		Name:          "ogen.enum",
		Tag:           "bytes,60030,opt,name=enum",
		Filename:      "ogen/ogen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         60030,
		Name:          "ogen.message",
		Tag:           "bytes,60030,opt,name=message",
		Filename:      "ogen/ogen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         60030,
		Name:          "ogen.field",
		Tag:           "bytes,60030,opt,name=field",
		Filename:      "ogen/ogen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*OneofOptions)(nil),
		Field:         60030,
		Name:          "ogen.oneof",
		Tag:           "bytes,60030,opt,name=oneof",
		Filename:      "ogen/ogen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceOptions)(nil),
		Field:         60030,
		Name:          "ogen.service",
		Tag:           "bytes,60030,opt,name=service",
		Filename:      "ogen/ogen.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*MethodOptions)(nil),
		Field:         60030,
		Name:          "ogen.method",
		Tag:           "bytes,60030,opt,name=method",
		Filename:      "ogen/ogen.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional ogen.FileOptions file = 60030;
	E_File = &file_ogen_ogen_proto_extTypes[0]
)

// Extension fields to descriptorpb.EnumOptions.
var (
	// optional ogen.SchemaOptions enum = 60030;
	E_Enum = &file_ogen_ogen_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional ogen.MessageOptions message = 60030;
	E_Message = &file_ogen_ogen_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional ogen.FieldOptions field = 60030;
	E_Field = &file_ogen_ogen_proto_extTypes[3]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// optional ogen.OneofOptions oneof = 60030;
	E_Oneof = &file_ogen_ogen_proto_extTypes[4]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional ogen.ServiceOptions service = 60030;
	E_Service = &file_ogen_ogen_proto_extTypes[5]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional ogen.MethodOptions method = 60030;
	E_Method = &file_ogen_ogen_proto_extTypes[6]
)

var File_ogen_ogen_proto protoreflect.FileDescriptor

const file_ogen_ogen_proto_rawDesc = "" +
	"\n" +
	"\x0fogen/ogen.proto\x12\x04ogen\x1a google/protobuf/descriptor.proto\"7\n" +
	"\vNamedString\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"o\n" +
	"\x06Server\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensions\"B\n" +
	"\fExternalDocs\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"E\n" +
	"\aContact\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"/\n" +
	"\aLicense\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"t\n" +
	"\x03Tag\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x127\n" +
	"\rexternal_docs\x18\x03 \x01(\v2\x12.ogen.ExternalDocsR\fexternalDocs\">\n" +
	"\aGoIdent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vimport_path\x18\x02 \x01(\tR\n" +
	"importPath\"\x1d\n" +
	"\tSchemaRef\x12\x10\n" +
	"\x03ref\x18\x01 \x01(\tR\x03ref\"\xce\x03\n" +
	"\rSchemaOptions\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fdefault_json\x18\x03 \x01(\tR\vdefaultJson\x12#\n" +
	"\rexamples_json\x18\x04 \x03(\tR\fexamplesJson\x12\x1b\n" +
	"\tenum_json\x18\x05 \x03(\tR\benumJson\x127\n" +
	"\rstring_format\x18\n" +
	" \x01(\x0e2\x12.ogen.StringFormatR\fstringFormat\x12#\n" +
	"\rcustom_format\x18\v \x01(\tR\fcustomFormat\x12\x1f\n" +
	"\bnullable\x18\x14 \x01(\bH\x00R\bnullable\x88\x01\x01\x12 \n" +
	"\tread_only\x18\x15 \x01(\bH\x01R\breadOnly\x88\x01\x01\x12\"\n" +
	"\n" +
	"write_only\x18\x16 \x01(\bH\x02R\twriteOnly\x88\x01\x01\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensionsB\v\n" +
	"\t_nullableB\f\n" +
	"\n" +
	"_read_onlyB\r\n" +
	"\v_write_only\"\xf5\x05\n" +
	"\vFileOptions\x12)\n" +
	"\x10generate_openapi\x18\x01 \x01(\bR\x0fgenerateOpenapi\x12#\n" +
	"\rgenerate_ogen\x18\x02 \x01(\bR\fgenerateOgen\x12/\n" +
	"\x13generate_converters\x18\x03 \x01(\bR\x12generateConverters\x12'\n" +
	"\x0fopenapi_version\x18\n" +
	" \x01(\tR\x0eopenapiVersion\x12\x14\n" +
	"\x05title\x18\v \x01(\tR\x05title\x12\x18\n" +
	"\aversion\x18\f \x01(\tR\aversion\x12\x18\n" +
	"\asummary\x18\r \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\x12(\n" +
	"\x10terms_of_service\x18\x0f \x01(\tR\x0etermsOfService\x12'\n" +
	"\acontact\x18\x10 \x01(\v2\r.ogen.ContactR\acontact\x12'\n" +
	"\alicense\x18\x11 \x01(\v2\r.ogen.LicenseR\alicense\x12&\n" +
	"\aservers\x18\x12 \x03(\v2\f.ogen.ServerR\aservers\x12\x1d\n" +
	"\x04tags\x18\x13 \x03(\v2\t.ogen.TagR\x04tags\x127\n" +
	"\rexternal_docs\x18\x14 \x01(\v2\x12.ogen.ExternalDocsR\fexternalDocs\x12%\n" +
	"\x0eopenapi_output\x18\x1e \x01(\tR\ropenapiOutput\x12\x1f\n" +
	"\vogen_target\x18\x1f \x01(\tR\n" +
	"ogenTarget\x12!\n" +
	"\fogen_package\x18  \x01(\tR\vogenPackage\x12*\n" +
	"\x11ogen_package_name\x18\" \x01(\tR\x0fogenPackageName\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensionsJ\x04\b!\x10\"J\x04\b#\x10$\"\x88\x04\n" +
	"\x0eMessageOptions\x12\x12\n" +
	"\x04omit\x18\x01 \x01(\bR\x04omit\x12\x1f\n" +
	"\vschema_name\x18\x02 \x01(\tR\n" +
	"schemaName\x12+\n" +
	"\x06schema\x18\x03 \x01(\v2\x13.ogen.SchemaOptionsR\x06schema\x12;\n" +
	"\x12override_ogen_type\x18\n" +
	" \x01(\v2\r.ogen.GoIdentR\x10overrideOgenType\x128\n" +
	"\x15additional_properties\x18\x14 \x01(\bH\x00R\x14additionalProperties\x88\x01\x01\x12Q\n" +
	"\x1cadditional_properties_schema\x18\x15 \x01(\v2\x0f.ogen.SchemaRefR\x1aadditionalPropertiesSchema\x125\n" +
	"\x16discriminator_property\x18\x16 \x01(\tR\x15discriminatorProperty\x12F\n" +
	"\x15discriminator_mapping\x18\x17 \x03(\v2\x11.ogen.NamedStringR\x14discriminatorMapping\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensionsB\x18\n" +
	"\x16_additional_properties\"\xe0\x02\n" +
	"\fFieldOptions\x12\x12\n" +
	"\x04omit\x18\x01 \x01(\bR\x04omit\x12\x1f\n" +
	"\brequired\x18\x02 \x01(\bH\x00R\brequired\x88\x01\x01\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x06schema\x18\x04 \x01(\v2\x13.ogen.SchemaOptionsR\x06schema\x12;\n" +
	"\x12override_ogen_type\x18\n" +
	" \x01(\v2\r.ogen.GoIdentR\x10overrideOgenType\x12$\n" +
	"\x0eenum_as_string\x18\v \x01(\bR\fenumAsString\x12\x1e\n" +
	"\venum_as_int\x18\f \x01(\bR\tenumAsInt\x12\x17\n" +
	"\ago_name\x18\r \x01(\tR\x06goName\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensionsB\v\n" +
	"\t_required\"\xf2\x01\n" +
	"\fOneofOptions\x126\n" +
	"\vschema_mode\x18\x01 \x01(\x0e2\x15.ogen.OneofSchemaModeR\n" +
	"schemaMode\x125\n" +
	"\x16discriminator_property\x18\x02 \x01(\tR\x15discriminatorProperty\x12F\n" +
	"\x15discriminator_mapping\x18\x03 \x03(\v2\x11.ogen.NamedStringR\x14discriminatorMapping\x12+\n" +
	"\x06schema\x18\x04 \x01(\v2\x13.ogen.SchemaOptionsR\x06schema\"\xd6\x01\n" +
	"\x0eServiceOptions\x12\x12\n" +
	"\x04omit\x18\x01 \x01(\bR\x04omit\x12\x1f\n" +
	"\vpath_prefix\x18\x02 \x01(\tR\n" +
	"pathPrefix\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12&\n" +
	"\aservers\x18\x05 \x03(\v2\f.ogen.ServerR\aservers\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensions\"\xfe\x01\n" +
	"\vRequestBody\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x1a\n" +
	"\brequired\x18\x02 \x01(\bR\brequired\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"field_path\x18\x04 \x01(\tR\tfieldPath\x12<\n" +
	"\x10media_extensions\x18\x05 \x03(\v2\x11.ogen.NamedStringR\x0fmediaExtensions\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensions\"\xdc\x01\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\x12\x1d\n" +
	"\n" +
	"field_path\x18\x04 \x01(\tR\tfieldPath\x12'\n" +
	"\x06schema\x18\x05 \x01(\v2\x0f.ogen.SchemaRefR\x06schema\x12+\n" +
	"\aheaders\x18\x06 \x03(\v2\x11.ogen.NamedStringR\aheaders\"\xac\x02\n" +
	"\x10ParameterBinding\x12\x1d\n" +
	"\n" +
	"field_path\x18\x01 \x01(\tR\tfieldPath\x12'\n" +
	"\x02in\x18\x02 \x01(\x0e2\x17.ogen.ParameterLocationR\x02in\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1f\n" +
	"\brequired\x18\x04 \x01(\bH\x00R\brequired\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12+\n" +
	"\x06schema\x18\x06 \x01(\v2\x13.ogen.SchemaOptionsR\x06schema\x12\x14\n" +
	"\x05style\x18\a \x01(\tR\x05style\x12\x1d\n" +
	"\aexplode\x18\b \x01(\bH\x01R\aexplode\x88\x01\x01B\v\n" +
	"\t_requiredB\n" +
	"\n" +
	"\b_explode\"$\n" +
	"\x0eWebhookOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xa4\x04\n" +
	"\rMethodOptions\x12\x12\n" +
	"\x04omit\x18\x01 \x01(\bR\x04omit\x121\n" +
	"\vhttp_method\x18\x02 \x01(\x0e2\x10.ogen.HttpMethodR\n" +
	"httpMethod\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12!\n" +
	"\foperation_id\x18\x04 \x01(\tR\voperationId\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\x12\x1e\n" +
	"\n" +
	"deprecated\x18\b \x01(\bR\n" +
	"deprecated\x12.\n" +
	"\awebhook\x18\t \x01(\v2\x14.ogen.WebhookOptionsR\awebhook\x124\n" +
	"\frequest_body\x18\x14 \x01(\v2\x11.ogen.RequestBodyR\vrequestBody\x126\n" +
	"\n" +
	"parameters\x18\x15 \x03(\v2\x16.ogen.ParameterBindingR\n" +
	"parameters\x12,\n" +
	"\tresponses\x18\x16 \x03(\v2\x0e.ogen.ResponseR\tresponses\x12&\n" +
	"\aservers\x18\x1e \x03(\v2\f.ogen.ServerR\aservers\x121\n" +
	"\n" +
	"extensions\x18d \x03(\v2\x11.ogen.NamedStringR\n" +
	"extensions*\xde\x01\n" +
	"\n" +
	"HttpMethod\x12\x1b\n" +
	"\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHTTP_METHOD_GET\x10\x01\x12\x14\n" +
	"\x10HTTP_METHOD_POST\x10\x02\x12\x13\n" +
	"\x0fHTTP_METHOD_PUT\x10\x03\x12\x15\n" +
	"\x11HTTP_METHOD_PATCH\x10\x04\x12\x16\n" +
	"\x12HTTP_METHOD_DELETE\x10\x05\x12\x14\n" +
	"\x10HTTP_METHOD_HEAD\x10\x06\x12\x17\n" +
	"\x13HTTP_METHOD_OPTIONS\x10\a\x12\x15\n" +
	"\x11HTTP_METHOD_TRACE\x10\b*\xb0\x01\n" +
	"\x11ParameterLocation\x12\"\n" +
	"\x1ePARAMETER_LOCATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17PARAMETER_LOCATION_PATH\x10\x01\x12\x1c\n" +
	"\x18PARAMETER_LOCATION_QUERY\x10\x02\x12\x1d\n" +
	"\x19PARAMETER_LOCATION_HEADER\x10\x03\x12\x1d\n" +
	"\x19PARAMETER_LOCATION_COOKIE\x10\x04*\xb5\x04\n" +
	"\fStringFormat\x12\x1d\n" +
	"\x19STRING_FORMAT_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12STRING_FORMAT_BYTE\x10\x01\x12\x18\n" +
	"\x14STRING_FORMAT_BINARY\x10\x02\x12\x16\n" +
	"\x12STRING_FORMAT_DATE\x10\x03\x12\x1b\n" +
	"\x17STRING_FORMAT_DATE_TIME\x10\x04\x12\x16\n" +
	"\x12STRING_FORMAT_TIME\x10\x05\x12\x1a\n" +
	"\x16STRING_FORMAT_DURATION\x10\x06\x12\x16\n" +
	"\x12STRING_FORMAT_UUID\x10\a\x12\x14\n" +
	"\x10STRING_FORMAT_IP\x10\b\x12\x16\n" +
	"\x12STRING_FORMAT_IPV4\x10\t\x12\x16\n" +
	"\x12STRING_FORMAT_IPV6\x10\n" +
	"\x12\x15\n" +
	"\x11STRING_FORMAT_URI\x10\v\x12\x17\n" +
	"\x13STRING_FORMAT_EMAIL\x10\f\x12\x1a\n" +
	"\x16STRING_FORMAT_HOSTNAME\x10\r\x12\x16\n" +
	"\x12STRING_FORMAT_UNIX\x10\x0e\x12\x1e\n" +
	"\x1aSTRING_FORMAT_UNIX_SECONDS\x10\x0f\x12\x1c\n" +
	"\x18STRING_FORMAT_UNIX_MILLI\x10\x10\x12\x1c\n" +
	"\x18STRING_FORMAT_UNIX_MICRO\x10\x11\x12\x1b\n" +
	"\x17STRING_FORMAT_UNIX_NANO\x10\x12\x12\x17\n" +
	"\x13STRING_FORMAT_INT32\x10\x13\x12\x17\n" +
	"\x13STRING_FORMAT_INT64\x10\x14*\x8e\x01\n" +
	"\x0fOneofSchemaMode\x12!\n" +
	"\x1dONEOF_SCHEMA_MODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ONEOF_SCHEMA_MODE_ONE_OF\x10\x01\x12\x1c\n" +
	"\x18ONEOF_SCHEMA_MODE_ANY_OF\x10\x02\x12\x1c\n" +
	"\x18ONEOF_SCHEMA_MODE_OBJECT\x10\x03:E\n" +
	"\x04file\x12\x1c.google.protobuf.FileOptions\x18\xfe\xd4\x03 \x01(\v2\x11.ogen.FileOptionsR\x04file:G\n" +
	"\x04enum\x12\x1c.google.protobuf.EnumOptions\x18\xfe\xd4\x03 \x01(\v2\x13.ogen.SchemaOptionsR\x04enum:Q\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xfe\xd4\x03 \x01(\v2\x14.ogen.MessageOptionsR\amessage:I\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xfe\xd4\x03 \x01(\v2\x12.ogen.FieldOptionsR\x05field:I\n" +
	"\x05oneof\x12\x1d.google.protobuf.OneofOptions\x18\xfe\xd4\x03 \x01(\v2\x12.ogen.OneofOptionsR\x05oneof:Q\n" +
	"\aservice\x12\x1f.google.protobuf.ServiceOptions\x18\xfe\xd4\x03 \x01(\v2\x14.ogen.ServiceOptionsR\aservice:M\n" +
	"\x06method\x12\x1e.google.protobuf.MethodOptions\x18\xfe\xd4\x03 \x01(\v2\x13.ogen.MethodOptionsR\x06methodB)Z'github.com/yaroher/protoc-gen-ogen/ogenb\x06proto3"

var (
	file_ogen_ogen_proto_rawDescOnce sync.Once
	file_ogen_ogen_proto_rawDescData []byte
)

func file_ogen_ogen_proto_rawDescGZIP() []byte {
	file_ogen_ogen_proto_rawDescOnce.Do(func() {
		file_ogen_ogen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ogen_ogen_proto_rawDesc), len(file_ogen_ogen_proto_rawDesc)))
	})
	return file_ogen_ogen_proto_rawDescData
}

var file_ogen_ogen_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ogen_ogen_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_ogen_ogen_proto_goTypes = []any{
	(HttpMethod)(0),                     // 0: ogen.HttpMethod
	(ParameterLocation)(0),              // 1: ogen.ParameterLocation
	(StringFormat)(0),                   // 2: ogen.StringFormat
	(OneofSchemaMode)(0),                // 3: ogen.OneofSchemaMode
	(*NamedString)(nil),                 // 4: ogen.NamedString
	(*Server)(nil),                      // 5: ogen.Server
	(*ExternalDocs)(nil),                // 6: ogen.ExternalDocs
	(*Contact)(nil),                     // 7: ogen.Contact
	(*License)(nil),                     // 8: ogen.License
	(*Tag)(nil),                         // 9: ogen.Tag
	(*GoIdent)(nil),                     // 10: ogen.GoIdent
	(*SchemaRef)(nil),                   // 11: ogen.SchemaRef
	(*SchemaOptions)(nil),               // 12: ogen.SchemaOptions
	(*FileOptions)(nil),                 // 13: ogen.FileOptions
	(*MessageOptions)(nil),              // 14: ogen.MessageOptions
	(*FieldOptions)(nil),                // 15: ogen.FieldOptions
	(*OneofOptions)(nil),                // 16: ogen.OneofOptions
	(*ServiceOptions)(nil),              // 17: ogen.ServiceOptions
	(*RequestBody)(nil),                 // 18: ogen.RequestBody
	(*Response)(nil),                    // 19: ogen.Response
	(*ParameterBinding)(nil),            // 20: ogen.ParameterBinding
	(*WebhookOptions)(nil),              // 21: ogen.WebhookOptions
	(*MethodOptions)(nil),               // 22: ogen.MethodOptions
	(*descriptorpb.FileOptions)(nil),    // 23: google.protobuf.FileOptions
	(*descriptorpb.EnumOptions)(nil),    // 24: google.protobuf.EnumOptions
	(*descriptorpb.MessageOptions)(nil), // 25: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 26: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil),   // 27: google.protobuf.OneofOptions
	(*descriptorpb.ServiceOptions)(nil), // 28: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 29: google.protobuf.MethodOptions
}
var file_ogen_ogen_proto_depIdxs = []int32{
	4,  // 0: ogen.Server.extensions:type_name -> ogen.NamedString
	6,  // 1: ogen.Tag.external_docs:type_name -> ogen.ExternalDocs
	2,  // 2: ogen.SchemaOptions.string_format:type_name -> ogen.StringFormat
	4,  // 3: ogen.SchemaOptions.extensions:type_name -> ogen.NamedString
	7,  // 4: ogen.FileOptions.contact:type_name -> ogen.Contact
	8,  // 5: ogen.FileOptions.license:type_name -> ogen.License
	5,  // 6: ogen.FileOptions.servers:type_name -> ogen.Server
	9,  // 7: ogen.FileOptions.tags:type_name -> ogen.Tag
	6,  // 8: ogen.FileOptions.external_docs:type_name -> ogen.ExternalDocs
	4,  // 9: ogen.FileOptions.extensions:type_name -> ogen.NamedString
	12, // 10: ogen.MessageOptions.schema:type_name -> ogen.SchemaOptions
	10, // 11: ogen.MessageOptions.override_ogen_type:type_name -> ogen.GoIdent
	11, // 12: ogen.MessageOptions.additional_properties_schema:type_name -> ogen.SchemaRef
	4,  // 13: ogen.MessageOptions.discriminator_mapping:type_name -> ogen.NamedString
	4,  // 14: ogen.MessageOptions.extensions:type_name -> ogen.NamedString
	12, // 15: ogen.FieldOptions.schema:type_name -> ogen.SchemaOptions
	10, // 16: ogen.FieldOptions.override_ogen_type:type_name -> ogen.GoIdent
	4,  // 17: ogen.FieldOptions.extensions:type_name -> ogen.NamedString
	3,  // 18: ogen.OneofOptions.schema_mode:type_name -> ogen.OneofSchemaMode
	4,  // 19: ogen.OneofOptions.discriminator_mapping:type_name -> ogen.NamedString
	12, // 20: ogen.OneofOptions.schema:type_name -> ogen.SchemaOptions
	5,  // 21: ogen.ServiceOptions.servers:type_name -> ogen.Server
	4,  // 22: ogen.ServiceOptions.extensions:type_name -> ogen.NamedString
	4,  // 23: ogen.RequestBody.media_extensions:type_name -> ogen.NamedString
	4,  // 24: ogen.RequestBody.extensions:type_name -> ogen.NamedString
	11, // 25: ogen.Response.schema:type_name -> ogen.SchemaRef
	4,  // 26: ogen.Response.headers:type_name -> ogen.NamedString
	1,  // 27: ogen.ParameterBinding.in:type_name -> ogen.ParameterLocation
	12, // 28: ogen.ParameterBinding.schema:type_name -> ogen.SchemaOptions
	0,  // 29: ogen.MethodOptions.http_method:type_name -> ogen.HttpMethod
	21, // 30: ogen.MethodOptions.webhook:type_name -> ogen.WebhookOptions
	18, // 31: ogen.MethodOptions.request_body:type_name -> ogen.RequestBody
	20, // 32: ogen.MethodOptions.parameters:type_name -> ogen.ParameterBinding
	19, // 33: ogen.MethodOptions.responses:type_name -> ogen.Response
	5,  // 34: ogen.MethodOptions.servers:type_name -> ogen.Server
	4,  // 35: ogen.MethodOptions.extensions:type_name -> ogen.NamedString
	23, // 36: ogen.file:extendee -> google.protobuf.FileOptions
	24, // 37: ogen.enum:extendee -> google.protobuf.EnumOptions
	25, // 38: ogen.message:extendee -> google.protobuf.MessageOptions
	26, // 39: ogen.field:extendee -> google.protobuf.FieldOptions
	27, // 40: ogen.oneof:extendee -> google.protobuf.OneofOptions
	28, // 41: ogen.service:extendee -> google.protobuf.ServiceOptions
	29, // 42: ogen.method:extendee -> google.protobuf.MethodOptions
	13, // 43: ogen.file:type_name -> ogen.FileOptions
	12, // 44: ogen.enum:type_name -> ogen.SchemaOptions
	14, // 45: ogen.message:type_name -> ogen.MessageOptions
	15, // 46: ogen.field:type_name -> ogen.FieldOptions
	16, // 47: ogen.oneof:type_name -> ogen.OneofOptions
	17, // 48: ogen.service:type_name -> ogen.ServiceOptions
	22, // 49: ogen.method:type_name -> ogen.MethodOptions
	50, // [50:50] is the sub-list for method output_type
	50, // [50:50] is the sub-list for method input_type
	43, // [43:50] is the sub-list for extension type_name
	36, // [36:43] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_ogen_ogen_proto_init() }
func file_ogen_ogen_proto_init() {
	if File_ogen_ogen_proto != nil {
		return
	}
	file_ogen_ogen_proto_msgTypes[8].OneofWrappers = []any{}
	file_ogen_ogen_proto_msgTypes[10].OneofWrappers = []any{}
	file_ogen_ogen_proto_msgTypes[11].OneofWrappers = []any{}
	file_ogen_ogen_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ogen_ogen_proto_rawDesc), len(file_ogen_ogen_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 7,
			NumServices:   0,
		},
		GoTypes:           file_ogen_ogen_proto_goTypes,
		DependencyIndexes: file_ogen_ogen_proto_depIdxs,
		EnumInfos:         file_ogen_ogen_proto_enumTypes,
		MessageInfos:      file_ogen_ogen_proto_msgTypes,
		ExtensionInfos:    file_ogen_ogen_proto_extTypes,
	}.Build()
	File_ogen_ogen_proto = out.File
	file_ogen_ogen_proto_goTypes = nil
	file_ogen_ogen_proto_depIdxs = nil
}
